// ===========================================================================
// Embedded frontend bundle.
//
// The HTTP controller serves the React UI from these bytes by default, so
// `dyson listen` works from anywhere on disk.
//
// The `ASSETS` table itself is generated by `crates/dyson/build.rs`, which
// walks `web/dist/` after `npm run build` and emits one entry per file.
// Hashed asset filenames from Vite land here verbatim; `index.html` at
// the root of the bundle is what `/` serves.
// ===========================================================================

include!(concat!(env!("OUT_DIR"), "/web_assets.rs"));

/// Look up an embedded asset by URL path.  Returns `(bytes, content-type)`
/// or `None`.
pub fn lookup(path: &str) -> Option<(&'static [u8], &'static str)> {
    let key = if path == "/" { "index.html" } else { path.trim_start_matches('/') };
    for (p, bytes, ct) in ASSETS {
        if *p == key {
            return Some((bytes, ct));
        }
    }
    None
}
