//! Runtime configuration after a Cube snapshot restore.
//!
//! Snapshot processes retain their warmup environment. Swarm supplies the live
//! identity, providers, model selection, and service credentials here instead.
//! The handler updates IDENTITY.md and commits one atomic configuration patch,
//! then reloads settings for subsequent turns.
//!
//! `auth` owns the per-instance configure secret; `config` owns document patches.
//! State replay, skill management, lifecycle, and cost backfill have separate
//! endpoint modules. The outer HTTP router retains bearer and CSRF enforcement.

use std::path::Path;

use hyper::Request;
use serde::Deserialize;
use serde_json::Value;

use crate::config::Settings;

use super::super::responses::{
    Resp, bad_request, json_ok, json_status, open_workspace, read_json_capped, unauthorized,
};
use super::super::state::HttpState;

/// Cap for the configure body.  Generous for very long task prompts
/// but small enough to swat away accidental large payloads.
const MAX_CONFIGURE_BODY: usize = 64 * 1024;

#[derive(Debug, Deserialize)]
pub(super) struct ConfigureBody {
    /// New employee name (e.g. "PR reviewer for foo/bar").
    /// Folded into IDENTITY.md as `Name: <value>`.
    #[serde(default)]
    name: Option<String>,
    /// New mission text.  Folded into IDENTITY.md under a "## Mission"
    /// section so the agent reads it via `Workspace::system_prompt`
    /// on every turn.
    #[serde(default)]
    task: Option<String>,
    /// Full IDENTITY.md replacement.  This is intentionally separate
    /// from `task`: the task field is plain mission text and must not
    /// be able to overwrite the whole identity document by looking like
    /// markdown generated by another system.
    #[serde(default)]
    identity_doc: Option<String>,
    /// New ordered model list.  First entry becomes the primary; the
    /// full list is written to the Swarm-owned provider's `models`
    /// in dyson.json so the next `HotReloader::check` picks it up.
    /// Empty list is a no-op (existing config is left alone).
    #[serde(default)]
    models: Vec<String>,
    /// Provider entry the swarm-owned model list/token/base URL belong to.
    /// Older Swarm callers omit this field; credential-bearing legacy payloads
    /// are mapped to the stable `openrouter` entry. Other callers fall back to
    /// `agent.provider`.
    #[serde(default)]
    provider_name: Option<String>,
    /// Swarm-owned active chat provider restored after a managed instance is
    /// recreated. Distinct from `provider_name`, which names the stable Swarm
    /// proxy entry being patched.
    #[serde(default)]
    active_provider: Option<String>,
    /// Model paired with `active_provider`. Partial pairs are rejected.
    #[serde(default)]
    active_model: Option<String>,
    /// Swarm-side instance id.  Surfaced in IDENTITY.md as
    /// `Swarm instance id: <value>` so the agent can reference it
    /// in tool calls back to swarm.
    #[serde(default)]
    instance_id: Option<String>,
    /// Replacement value for `providers.<agent.provider>.api_key` —
    /// the per-instance proxy_token swarm minted at create time.
    /// Without this, the dyson.json keeps the boot-time
    /// `warmup-placeholder` literal as its api_key (Cube freezes
    /// `/proc/self/environ` at warmup, so the `SWARM_PROXY_TOKEN`
    /// env swarm injects on instance create never reaches the
    /// running dyson process).
    #[serde(default)]
    proxy_token: Option<crate::tokens::ProxyToken>,
    /// Replacement value for `providers.<agent.provider>.base_url` —
    /// swarm's `/llm` URL the agent should call.  Same root cause
    /// as `proxy_token`: the boot-time value is empty / loopback
    /// and Cube's snapshot freeze means swarm can't ride env vars
    /// to fix it.
    #[serde(default)]
    proxy_base: Option<String>,
    /// Name to register the image-generation provider under in
    /// `providers.<image_provider_name>`.  Distinct from
    /// `agent.provider` (chat) so the two can run with different
    /// `LlmProvider` types — only `Gemini` and `OpenRouter` are wired
    /// for image generation today.  When swarm pushes this it always
    /// arrives alongside `image_provider_block`,
    /// `image_generation_provider`, and `image_generation_model`;
    /// individually-set fields are still patched so callers can do
    /// partial updates if they want.
    #[serde(default)]
    image_provider_name: Option<String>,
    /// Full provider entry to insert under `providers.<image_provider_name>`.
    /// Shape mirrors what the dyson-side loader accepts:
    /// `{ "type": "openrouter", "base_url": "...", "api_key": "...", "models": [...] }`.
    /// Existing entries with the same name are replaced.
    #[serde(default)]
    image_provider_block: Option<serde_json::Value>,
    /// Sets `agent.image_generation_provider`.  Usually equal to
    /// `image_provider_name`, but kept independent so a future
    /// caller could point the field at an already-registered
    /// provider without re-uploading its block.
    #[serde(default)]
    image_generation_provider: Option<String>,
    /// Sets `agent.image_generation_model` — the model id passed to
    /// the image-gen factory's `model_override`.  Without this the
    /// factory falls back to the provider's first `models` entry.
    #[serde(default)]
    image_generation_model: Option<String>,
    /// Reset the `skills` block in dyson.json to "use defaults".
    /// Removes the key entirely so the loader's
    /// no-skills-block branch fires and every builtin tool registers
    /// (`bash`, `read_file`, `image_generate`, etc.).  Originally
    /// added because earlier `dyson swarm` boots wrote
    /// `"skills": { "builtin": { "tools": [] } }`, which the loader
    /// parses as "register zero builtin tools" — every instance
    /// shipped without a single tool.  Setting this flag on a sweep
    /// is the retroactive fix.
    #[serde(default)]
    reset_skills: bool,
    /// Explicit builtin-tool allowlist.  When `Some`, dyson rewrites
    /// `skills.builtin.tools` to this exact list; the loader registers
    /// only those builtins.  An empty vec is meaningful — register
    /// zero builtins.  Distinct from `reset_skills` (which drops the
    /// block entirely).  When both are set, `tools` wins (a caller
    /// asking for a subset clearly does NOT want defaults).
    #[serde(default)]
    tools: Option<Vec<String>>,
    /// Per-server stanzas to write under top-level `mcp_servers.<name>`.
    /// Each value is the JSON the loader's `parse_mcp_servers` already
    /// understands — typically `{ url, headers, auth? }` for HTTP MCP.
    /// Swarm builds these with its own proxied URL + the per-instance
    /// bearer so the agent never sees the upstream URL or its
    /// credentials.  `None` leaves the existing block alone; an empty
    /// map clears it.  Replaces the whole block — incremental edits
    /// aren't supported (callers who want add/remove read the file first).
    #[serde(default)]
    mcp_servers: Option<serde_json::Map<String, Value>>,
    /// Full URL the agent's `Output::send_artefact` POSTs to.  Mirrors
    /// `SWARM_INGEST_URL` in the env envelope; pushed here because
    /// the cube's snapshot/restore freezes /proc/self/environ at
    /// warmup, same root cause `proxy_token` already needs a
    /// configure-push.  When set together with `ingest_token` (both
    /// non-empty), `state.ingest` is updated and subsequent
    /// `send_artefact` calls fire a fire-and-forget POST.  Empty or
    /// missing leaves the existing config alone — a re-push that
    /// only updates other fields shouldn't wipe ingest.
    #[serde(default)]
    ingest_url: Option<String>,
    /// Per-instance `it_<32hex>` bearer for the ingest endpoint.
    /// Mirrors `SWARM_INGEST_TOKEN`.  See `ingest_url` for posture.
    #[serde(default)]
    ingest_token: Option<crate::tokens::IngestToken>,
    /// Full URL the swarm-mode background state worker POSTs selected
    /// workspace files to. Mirrors `SWARM_STATE_SYNC_URL`; pushed here
    /// because warmup env is frozen for the running dyson process.
    #[serde(default)]
    state_sync_url: Option<String>,
    /// Per-instance `st_<32hex>` bearer for the state-file endpoint.
    #[serde(default)]
    state_sync_token: Option<crate::tokens::StateSyncToken>,
    /// Token-isolated Telegram proxy settings supplied by swarm.
    /// Patches/creates the Telegram controller in webhook mode.
    #[serde(default)]
    telegram_proxy: Option<TelegramProxyConfigure>,
}

#[derive(Debug, Deserialize)]
struct TelegramProxyConfigure {
    base_url: String,
    file_base_url: String,
    bearer: String,
    #[serde(default = "default_true")]
    enabled: bool,
}

fn default_true() -> bool {
    true
}

fn update_identity(snapshot: &Settings, body: &ConfigureBody) -> Result<bool, Box<Resp>> {
    if body.name.is_none()
        && body.task.is_none()
        && body.instance_id.is_none()
        && body.identity_doc.is_none()
    {
        return Ok(false);
    }
    let mut workspace = open_workspace(snapshot)?;
    if let Some(identity_doc) = body.identity_doc.as_deref() {
        if !looks_like_full_identity_doc(identity_doc) {
            return Err(Box::new(bad_request(
                "identity_doc must be a full IDENTITY.md document",
            )));
        }
        workspace.set("IDENTITY.md", identity_doc);
    } else {
        let existing = workspace.get("IDENTITY.md").unwrap_or_default();
        let prior_name = extract_field(&existing, "Name");
        let prior_instance = extract_field(&existing, "Swarm instance id");
        let prior_mission = extract_section(&existing, "Mission")
            .or_else(|| looks_like_full_identity_doc(&existing).then(|| existing.clone()));
        let merged = build_identity_md(
            body.name.as_deref().or(prior_name.as_deref()),
            body.instance_id.as_deref().or(prior_instance.as_deref()),
            body.task.as_deref().or(prior_mission.as_deref()),
        );
        workspace.set("IDENTITY.md", &merged);
    }
    workspace
        .save()
        .map_err(|error| Box::new(bad_request(&format!("workspace save failed: {error}"))))?;
    Ok(true)
}

async fn reload_patched_config(
    state: &HttpState,
    snapshot: &Settings,
    config_path: Option<&Path>,
    changed: bool,
) {
    let Some(path) = config_path.filter(|_| changed) else {
        return;
    };
    let path = path.to_path_buf();
    match tokio::task::spawn_blocking(move || crate::config::loader::load_settings(Some(&path)))
        .await
    {
        Ok(Ok(mut settings)) => {
            preserve_runtime_only_settings(&mut settings, snapshot);
            state.registry.reload(&settings, None);
            if let Ok(mut current) = state.settings.write() {
                *current = settings.clone();
            }
            crate::controller::publish_settings(std::sync::Arc::new(settings));
            tracing::info!("dyson.json patched + registry reloaded by /api/admin/configure");
        }
        Ok(Err(error)) => tracing::warn!(
            error = %error,
            "post-patch settings reload failed; falling back to polling HotReloader"
        ),
        Err(error) => tracing::warn!(
            error = %error,
            "post-patch settings reload worker failed; falling back to polling HotReloader"
        ),
    }
}

pub(super) async fn post(req: Request<hyper::body::Incoming>, state: &HttpState) -> Resp {
    // Pull the configure secret BEFORE consuming the body — the
    // header check runs first so an unauthenticated caller can't
    // make us read a 64 KiB body just to reject it.
    if let Some(resp) = authorize_configure(req.headers(), state).await {
        return resp;
    }

    let body: ConfigureBody = match read_json_capped(req, MAX_CONFIGURE_BODY).await {
        Ok(b) => b,
        Err(e) => return bad_request(&e),
    };
    if body
        .task
        .as_deref()
        .is_some_and(looks_like_full_identity_doc)
    {
        return bad_request("task must be mission text; use identity_doc for full IDENTITY.md");
    }
    let snapshot = state.settings_snapshot();

    // 1. Workspace: rewrite IDENTITY.md from the new fields.  Empty
    //    fields are skipped (so a configure carrying only `models`
    //    won't blank the existing identity).
    let identity_changed = match update_identity(&snapshot, &body) {
        Ok(changed) => changed,
        Err(response) => return *response,
    };

    // 2. dyson.json: patch the named Swarm provider's `models`, `api_key`,
    //    and/or `base_url` if the body supplies them.  All three
    //    targets share the same patch helper because the surface is
    //    a single named `providers` object — one
    //    read-modify-write keeps the file in a consistent state and
    //    the HotReloader fires once per change cluster instead of
    //    three times.  Empty / None on a field means "leave alone".
    let config_path = state.config_path();
    let has_config = config_path.is_some();
    let want_models = !body.models.is_empty();
    let want_api_key = has_text(
        body.proxy_token
            .as_ref()
            .map(crate::tokens::ProxyToken::as_str),
    );
    let want_base_url = has_text(body.proxy_base.as_deref());
    let provider_requested = want_models || want_api_key || want_base_url;
    let provider_applied = provider_requested && has_config;
    let models_applied = want_models && provider_applied;
    let active_selection = match (
        body.active_provider.as_deref().map(str::trim),
        body.active_model.as_deref().map(str::trim),
    ) {
        (None, None) => None,
        (Some(provider), Some(model)) if !provider.is_empty() && !model.is_empty() => {
            Some((provider, model))
        }
        _ => return bad_request("active_provider and active_model must be supplied together"),
    };
    let model_selection_applied = active_selection.is_some() && has_config;

    // 3. Image generation: register / replace the dedicated image
    //    provider block and point `agent.image_generation_*` at it.
    //    Independent of the chat patch above — the chat path's
    //    `agent.provider` is `openrouter` (LlmProvider::OpenAi under
    //    the hood) but the image factory dispatches on real
    //    LlmProvider variants, so the two need separate provider
    //    entries.  Existing dysons (created before this field was
    //    plumbed) get retroactively rewired by the swarm-side sweep
    //    that pushes a configure with these set.
    let want_image_block =
        has_text(body.image_provider_name.as_deref()) && body.image_provider_block.is_some();
    let want_image_provider = has_text(body.image_generation_provider.as_deref());
    let want_image_model = has_text(body.image_generation_model.as_deref());
    let image_requested = want_image_block || want_image_provider || want_image_model;
    let image_applied = image_requested && has_config;
    // 4. Skills: an explicit `tools` list rewrites
    //    `skills.builtin.tools` to that exact set; otherwise
    //    `reset_skills` drops the `skills` key so the loader's
    //    defaults path registers every builtin.  Independent of the
    //    chat / image patches — swarm's sweep flips one of these on
    //    every push so toolless instances self-heal on the next
    //    configure.  `tools` wins if both are set.
    let skills_requested = body.tools.is_some() || body.reset_skills;
    let skills_applied = skills_requested && has_config;

    // 5. MCP servers: replace the top-level `mcp_servers` block.  None
    //    leaves it alone; an empty map clears it.  Distinct from the
    //    skills block because MCP servers are a sibling key in the
    //    loader's `JsonRoot`, not nested under `skills`.
    let mcp_applied = body.mcp_servers.is_some() && has_config;
    let telegram_applied = body.telegram_proxy.is_some() && has_config;

    let config_patch = if let Some(path) = config_path {
        match patch_config_once(
            path,
            ConfigureConfigPatch {
                provider_name: body.provider_name.as_deref(),
                models: if want_models {
                    Some(body.models.as_slice())
                } else {
                    None
                },
                api_key: if want_api_key {
                    body.proxy_token
                        .as_ref()
                        .map(crate::tokens::ProxyToken::as_str)
                } else {
                    None
                },
                base_url: if want_base_url {
                    body.proxy_base.as_deref()
                } else {
                    None
                },
                active_selection,
                image_provider_block: if want_image_block {
                    body.image_provider_name
                        .as_deref()
                        .zip(body.image_provider_block.as_ref())
                } else {
                    None
                },
                image_provider: if want_image_provider {
                    body.image_generation_provider.as_deref()
                } else {
                    None
                },
                image_model: if want_image_model {
                    body.image_generation_model.as_deref()
                } else {
                    None
                },
                tools: body.tools.as_deref(),
                reset_skills: body.reset_skills,
                mcp_servers: body.mcp_servers.as_ref(),
                telegram_proxy: body.telegram_proxy.as_ref(),
                refresh_subscription_models: want_api_key || want_base_url,
            },
        )
        .await
        {
            Ok(patch) => patch,
            Err(e) => return bad_request(&format!("config patch failed: {e}")),
        }
    } else {
        AppliedConfigPatch::default()
    };
    let provider_changed = config_patch.provider_changed;
    let model_selection_changed = config_patch.model_selection_changed;
    let models_changed = provider_changed && want_models;
    let image_changed = config_patch.image_changed;
    let skills_changed = config_patch.skills_changed;
    let mcp_changed = config_patch.mcp_changed;
    let telegram_changed = config_patch.telegram_changed;

    let any_config_changed = provider_changed
        || model_selection_changed
        || image_changed
        || skills_changed
        || mcp_changed
        || telegram_changed;

    let swarm_patch = swarm_runtime_patch(
        body.proxy_base.as_deref(),
        body.proxy_token
            .as_ref()
            .map(crate::tokens::ProxyToken::as_str),
        body.instance_id.as_deref(),
    );
    let swarm_runtime_applied = swarm_patch.is_some();
    let swarm_runtime_changed = match &swarm_patch {
        Some(SwarmRuntimePatch::Set {
            proxy_url,
            proxy_token,
            instance_id,
        }) => {
            crate::swarm_cost::set_runtime_config_from_parts(proxy_url, proxy_token);
            let _ = instance_id;
            true
        }
        Some(SwarmRuntimePatch::Clear) => {
            crate::swarm_cost::set_runtime_config(None);
            true
        }
        _ => false,
    };

    // Eagerly reload the settings + ClientRegistry instead of waiting
    // for the 2s polling HotReloader to notice the mtime change.  Two
    // reasons this matters:
    //   1. Cube snapshot/restore freezes the dyson process — there's
    //      a real possibility the program-level hot-reload tokio task
    //      doesn't survive the resume cleanly, leaving the registry
    //      pinned to its warmup-time clients (api_key
    //      "warmup-placeholder", base_url api.openai.com).  The chat
    //      then 401s against api.openai.com on every turn.
    //   2. Even when the polling loop IS alive, a chat that fires
    //      between the patch and the next 2s tick caches the warmup
    //      client; the per-chat HotReloader's baseline is then
    //      post-patch, so subsequent turns see no change and never
    //      rebuild.  Eager reload closes the window entirely.
    reload_patched_config(state, &snapshot, config_path, any_config_changed).await;

    // Keep the runtime override aligned with the durable config. Without
    // this assignment an earlier UI switch can remain in memory and mask the
    // freshly restored selection in `/api/providers` until process restart.
    if let Some((provider, model)) = active_selection {
        let selection = match super::super::state::RuntimeModelSelection::new(
            provider.to_owned(),
            model.to_owned(),
        ) {
            Ok(selection) => selection,
            Err(error) => return bad_request(&error),
        };
        let mut slot = match state.runtime_model.lock() {
            Ok(guard) => guard,
            Err(poisoned) => poisoned.into_inner(),
        };
        *slot = Some(selection);
    }

    // Patch the runtime artefact-ingest target.  Both fields must be
    // non-empty in the same body to take effect — a partial body
    // (just `ingest_url` without a token) leaves the existing config
    // alone rather than landing a half-broken target.  Same posture
    // as the proxy_token / proxy_base patch: mutating in place keeps
    // a running `SseOutput` reading the live values without an
    // agent rebuild.  Both empty strings → clear the config (operator
    // turned ingest off explicitly).
    let ingest_patch = runtime_patch(
        body.ingest_url.as_deref(),
        body.ingest_token
            .as_ref()
            .map(crate::tokens::IngestToken::as_str),
    );
    let ingest_applied = ingest_patch.is_some();
    let ingest_changed = match &ingest_patch {
        Some(RuntimePatch::Set { url, token }) => {
            let cfg = super::super::state::IngestConfig {
                url: url.to_string(),
                token: token.to_string(),
            };
            if let Ok(mut g) = state.ingest.lock() {
                *g = Some(cfg);
            }
            true
        }
        Some(RuntimePatch::Clear) => {
            if let Ok(mut g) = state.ingest.lock() {
                *g = None;
            }
            true
        }
        _ => false,
    };
    let state_sync_patch = runtime_patch(
        body.state_sync_url.as_deref(),
        body.state_sync_token
            .as_ref()
            .map(crate::tokens::StateSyncToken::as_str),
    );
    let state_sync_applied = state_sync_patch.is_some();
    let state_sync_changed = match &state_sync_patch {
        Some(RuntimePatch::Set { url, token }) => {
            crate::swarm_state_sync::set_config(Some(crate::swarm_state_sync::StateSyncConfig {
                url: url.to_string(),
                token: token.to_string(),
            }));
            true
        }
        Some(RuntimePatch::Clear) => {
            crate::swarm_state_sync::set_config(None);
            true
        }
        _ => false,
    };
    json_ok(&serde_json::json!({
        "ok": true,
        "identity_updated": identity_changed,
        "models_updated": models_changed,
        "models_applied": models_applied,
        "provider_updated": provider_changed,
        "provider_applied": provider_applied,
        "model_selection_updated": model_selection_changed,
        "model_selection_applied": model_selection_applied,
        "image_generation_updated": image_changed,
        "image_generation_applied": image_applied,
        "skills_reset": skills_changed,
        "skills_applied": skills_applied,
        "mcp_servers_updated": mcp_changed,
        "mcp_servers_applied": mcp_applied,
        "telegram_updated": telegram_changed,
        "telegram_applied": telegram_applied,
        "ingest_updated": ingest_changed,
        "ingest_applied": ingest_applied,
        "state_sync_updated": state_sync_changed,
        "state_sync_applied": state_sync_applied,
        "swarm_runtime_updated": swarm_runtime_changed,
        "swarm_runtime_applied": swarm_runtime_applied,
    }))
}

fn preserve_runtime_only_settings(new_settings: &mut Settings, snapshot: &Settings) {
    // `sandbox_bypass` is deliberately CLI-only and never serialized
    // into dyson.json. Eager runtime reloads must carry it forward or
    // swarm instances inside Cube will try to build an OS sandbox and
    // exit because bwrap is not installed there.
    new_settings.sandbox_bypass = snapshot.sandbox_bypass.clone();
}

#[derive(Debug, PartialEq, Eq)]
enum RuntimePatch<'a> {
    Set { url: &'a str, token: &'a str },
    Clear,
}

#[derive(Debug, PartialEq, Eq)]
enum SwarmRuntimePatch<'a> {
    Set {
        proxy_url: &'a str,
        proxy_token: &'a str,
        instance_id: &'a str,
    },
    Clear,
}

fn has_text(value: Option<&str>) -> bool {
    value.is_some_and(|s| !s.is_empty())
}

fn runtime_patch<'a>(url: Option<&'a str>, token: Option<&'a str>) -> Option<RuntimePatch<'a>> {
    match (url, token) {
        (Some(url), Some(token)) if !url.is_empty() && !token.is_empty() => {
            Some(RuntimePatch::Set { url, token })
        }
        (Some(""), Some("")) => Some(RuntimePatch::Clear),
        _ => None,
    }
}

fn swarm_runtime_patch<'a>(
    proxy_url: Option<&'a str>,
    proxy_token: Option<&'a str>,
    instance_id: Option<&'a str>,
) -> Option<SwarmRuntimePatch<'a>> {
    match (proxy_url, proxy_token, instance_id) {
        (Some(proxy_url), Some(proxy_token), Some(instance_id))
            if !proxy_url.is_empty() && !proxy_token.is_empty() && !instance_id.is_empty() =>
        {
            Some(SwarmRuntimePatch::Set {
                proxy_url,
                proxy_token,
                instance_id,
            })
        }
        (Some(""), Some(""), Some("")) => Some(SwarmRuntimePatch::Clear),
        _ => None,
    }
}

/// Render the IDENTITY.md body in the same shape `dyson swarm` writes
/// at boot.  `Workspace::system_prompt()` injects the file under the
/// `## IDENTITY` section of the agent's system prompt, so the format
/// here is read by the model on every turn.
fn build_identity_md(
    name: Option<&str>,
    instance_id: Option<&str>,
    mission: Option<&str>,
) -> String {
    if let Some(m) = mission.filter(|s| looks_like_full_identity_doc(s)) {
        return m.to_owned();
    }
    let mut body = String::from("# Identity\n\n");
    if let Some(n) = name.filter(|s| !s.is_empty()) {
        body.push_str(&format!("Name: {n}\n"));
    }
    if let Some(id) = instance_id.filter(|s| !s.is_empty()) {
        body.push_str(&format!("Swarm instance id: {id}\n"));
    }
    if let Some(m) = mission.filter(|s| !s.is_empty()) {
        body.push_str(&format!("\n## Mission\n\n{m}\n"));
    }
    body
}

fn looks_like_full_identity_doc(body: &str) -> bool {
    let trimmed = body.trim_start();
    trimmed.starts_with("# IDENTITY.md") || trimmed.starts_with("# Identity")
}

/// Crude `Key: value` line scanner — good enough for the two top-of-file
/// fields IDENTITY.md uses.  Returns the trimmed value or None.
fn extract_field(body: &str, key: &str) -> Option<String> {
    let prefix = format!("{key}:");
    body.lines()
        .find_map(|l| l.strip_prefix(&prefix))
        .map(|s| s.trim().to_owned())
        .filter(|s| !s.is_empty())
}

/// Pull the body of a `## <name>` section up to the next `##` heading
/// or end of file.  Used to preserve existing mission text when a
/// configure carries only `name` / `instance_id`.
fn extract_section(body: &str, name: &str) -> Option<String> {
    let header = format!("## {name}");
    let mut found = false;
    let mut out = String::new();
    for line in body.lines() {
        if found {
            if line.starts_with("## ") {
                break;
            }
            out.push_str(line);
            out.push('\n');
        } else if line.trim() == header {
            found = true;
        }
    }
    let trimmed = out.trim().to_owned();
    if trimmed.is_empty() {
        None
    } else {
        Some(trimmed)
    }
}

mod auth;
use auth::authorize_configure;
pub use auth::preseed_configure_hash;

mod config;
use config::{AppliedConfigPatch, ConfigureConfigPatch, patch_config_once};

#[cfg(test)]
mod tests;

mod state_files;
pub(super) use state_files::post_state_file;

mod skills;
pub(super) use skills::{delete_skill, get_skills, post_skill_install};

mod lifecycle;
pub(super) use lifecycle::{get_idle, post_quiesce, post_unquiesce};

mod costs;
pub(super) use costs::post_cost_backfill;
