// ===========================================================================
// /api/admin/configure — runtime reconfigure of name / task / models.
//
// Why this exists: Cube takes the cube-template snapshot during the
// dyson-swarm warmup boot, when SWARM_MODEL / SWARM_TASK / etc are
// unset.  On instance create, Cube restores the snapshot — preserving
// the running dyson process's frozen `/proc/self/environ`, so the env
// envelope swarm injects on cube.create_sandbox never reaches the
// agent.  Result without this endpoint: every dyson instance shows
// "warmup-placeholder" as its model and no IDENTITY.md / mission.
//
// dyson-orchestrator's instance.create() POSTs here right after the
// sandbox flips Live with the real env (model list, task, name,
// instance id).  This handler:
//   1. Writes IDENTITY.md to the workspace — picked up by the
//      `HotReloader` on the next agent turn (no process restart).
//   2. Patches dyson.json's `providers.openrouter.models` (or the
//      configured agent provider) — also `HotReloader`-watched, so
//      the next agent build uses the new model list.
//
// Auth: same as every `/api/*` route — `state.auth` validates the
// inbound bearer.  When dyson booted in dangerous-no-auth (warmup),
// any caller is accepted, which is how swarm gets the very first
// configure call through after the snapshot restore (the dyson
// process still thinks it's in warmup mode).  The sandbox is
// network-isolated except via cubeproxy, so "any caller" is in
// practice "swarm via dyson_proxy".

use std::collections::HashMap;
use std::path::{Component, Path, PathBuf};
use std::sync::Arc;
use std::time::{Duration, Instant};

use base64::Engine;
use base64::engine::general_purpose::STANDARD as B64;
use hyper::body::Bytes;
use hyper::{Request, Response, StatusCode};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use sha2::{Digest, Sha256};
use tokio::io::AsyncWriteExt;
use tokio::sync::RwLock;

use crate::config::Settings;

use super::super::responses::{Resp, bad_request, boxed, json_ok, read_json_capped, unauthorized};
use super::super::state::HttpState;

/// Cap for the configure body.  Generous for very long task prompts
/// but small enough to swat away accidental large payloads.
const MAX_CONFIGURE_BODY: usize = 64 * 1024;

/// State replay carries base64 file bodies.  The sync worker caps source
/// files at 5 MiB, so 8 MiB leaves JSON/base64 headroom without turning
/// the admin surface into a bulk upload endpoint.
const MAX_STATE_FILE_BODY: usize = 8 * 1024 * 1024;

/// Package install payload is a validated SKILL.md body plus metadata.
/// Keep it above the swarm-side skill body cap to leave JSON overhead.
const MAX_SKILL_INSTALL_BODY: usize = 96 * 1024;
const MAX_COST_BACKFILL_BODY: usize = 1024;

/// Header swarm sends with the per-instance configure secret
/// (32-hex plaintext from `Uuid::new_v4().simple()`).  Dyson hashes
/// it on first sighting (TOFU) and verifies on every subsequent call.
const CONFIGURE_HEADER: &str = "x-swarm-configure";

/// Filename inside the dyson home dir that holds the argon2id hash
/// of the configure secret.  Lives next to `workspace/`, persists
/// across cube restores (it's in the writable layer).  PHC string
/// format (`$argon2id$v=19$...`) so argon2's verifier can re-derive
/// the salt.
const CONFIGURE_HASH_FILENAME: &str = "configure_secret_hash";
const CONFIGURE_VERIFY_CACHE_TTL: Duration = Duration::from_secs(30);

#[derive(Clone, Debug, Hash, PartialEq, Eq)]
struct ConfigureVerifyCacheKey {
    hash_path: PathBuf,
    secret_digest_prefix: [u8; 16],
    stored_digest_prefix: [u8; 16],
}

static CONFIGURE_AUTH_LOCK: std::sync::OnceLock<tokio::sync::Mutex<()>> =
    std::sync::OnceLock::new();
static CONFIGURE_VERIFY_CACHE: std::sync::OnceLock<
    std::sync::Mutex<HashMap<ConfigureVerifyCacheKey, Instant>>,
> = std::sync::OnceLock::new();

#[derive(Debug, Deserialize)]
pub(super) struct ConfigureBody {
    /// New employee name (e.g. "PR reviewer for foo/bar").
    /// Folded into IDENTITY.md as `Name: <value>`.
    #[serde(default)]
    name: Option<String>,
    /// New mission text.  Folded into IDENTITY.md under a "## Mission"
    /// section so the agent reads it via `Workspace::system_prompt`
    /// on every turn.
    #[serde(default)]
    task: Option<String>,
    /// Full IDENTITY.md replacement.  This is intentionally separate
    /// from `task`: the task field is plain mission text and must not
    /// be able to overwrite the whole identity document by looking like
    /// markdown generated by another system.
    #[serde(default)]
    identity_doc: Option<String>,
    /// New ordered model list.  First entry becomes the primary; the
    /// full list is written to `providers.<agent_provider>.models`
    /// in dyson.json so the next `HotReloader::check` picks it up.
    /// Empty list is a no-op (existing config is left alone).
    #[serde(default)]
    models: Vec<String>,
    /// Swarm-side instance id.  Surfaced in IDENTITY.md as
    /// `Swarm instance id: <value>` so the agent can reference it
    /// in tool calls back to swarm.
    #[serde(default)]
    instance_id: Option<String>,
    /// Replacement value for `providers.<agent.provider>.api_key` —
    /// the per-instance proxy_token swarm minted at create time.
    /// Without this, the dyson.json keeps the boot-time
    /// `warmup-placeholder` literal as its api_key (Cube freezes
    /// `/proc/self/environ` at warmup, so the `SWARM_PROXY_TOKEN`
    /// env swarm injects on instance create never reaches the
    /// running dyson process).
    #[serde(default)]
    proxy_token: Option<String>,
    /// Replacement value for `providers.<agent.provider>.base_url` —
    /// swarm's `/llm` URL the agent should call.  Same root cause
    /// as `proxy_token`: the boot-time value is empty / loopback
    /// and Cube's snapshot freeze means swarm can't ride env vars
    /// to fix it.
    #[serde(default)]
    proxy_base: Option<String>,
    /// Name to register the image-generation provider under in
    /// `providers.<image_provider_name>`.  Distinct from
    /// `agent.provider` (chat) so the two can run with different
    /// `LlmProvider` types — only `Gemini` and `OpenRouter` are wired
    /// for image generation today.  When swarm pushes this it always
    /// arrives alongside `image_provider_block`,
    /// `image_generation_provider`, and `image_generation_model`;
    /// individually-set fields are still patched so callers can do
    /// partial updates if they want.
    #[serde(default)]
    image_provider_name: Option<String>,
    /// Full provider entry to insert under `providers.<image_provider_name>`.
    /// Shape mirrors what the dyson-side loader accepts:
    /// `{ "type": "openrouter", "base_url": "...", "api_key": "...", "models": [...] }`.
    /// Existing entries with the same name are replaced.
    #[serde(default)]
    image_provider_block: Option<serde_json::Value>,
    /// Sets `agent.image_generation_provider`.  Usually equal to
    /// `image_provider_name`, but kept independent so a future
    /// caller could point the field at an already-registered
    /// provider without re-uploading its block.
    #[serde(default)]
    image_generation_provider: Option<String>,
    /// Sets `agent.image_generation_model` — the model id passed to
    /// the image-gen factory's `model_override`.  Without this the
    /// factory falls back to the provider's first `models` entry.
    #[serde(default)]
    image_generation_model: Option<String>,
    /// Reset the `skills` block in dyson.json to "use defaults".
    /// Removes the key entirely so the loader's
    /// no-skills-block branch fires and every builtin tool registers
    /// (`bash`, `read_file`, `image_generate`, etc.).  Originally
    /// added because earlier `dyson swarm` boots wrote
    /// `"skills": { "builtin": { "tools": [] } }`, which the loader
    /// parses as "register zero builtin tools" — every instance
    /// shipped without a single tool.  Setting this flag on a sweep
    /// is the retroactive fix.
    #[serde(default)]
    reset_skills: bool,
    /// Explicit builtin-tool allowlist.  When `Some`, dyson rewrites
    /// `skills.builtin.tools` to this exact list; the loader registers
    /// only those builtins.  An empty vec is meaningful — register
    /// zero builtins.  Distinct from `reset_skills` (which drops the
    /// block entirely).  When both are set, `tools` wins (a caller
    /// asking for a subset clearly does NOT want defaults).
    #[serde(default)]
    tools: Option<Vec<String>>,
    /// Per-server stanzas to write under top-level `mcp_servers.<name>`.
    /// Each value is the JSON the loader's `parse_mcp_servers` already
    /// understands — typically `{ url, headers, auth? }` for HTTP MCP.
    /// Swarm builds these with its own proxied URL + the per-instance
    /// bearer so the agent never sees the upstream URL or its
    /// credentials.  `None` leaves the existing block alone; an empty
    /// map clears it.  Replaces the whole block — incremental edits
    /// aren't supported (callers who want add/remove read the file first).
    #[serde(default)]
    mcp_servers: Option<serde_json::Map<String, Value>>,
    /// Full URL the agent's `Output::send_artefact` POSTs to.  Mirrors
    /// `SWARM_INGEST_URL` in the env envelope; pushed here because
    /// the cube's snapshot/restore freezes /proc/self/environ at
    /// warmup, same root cause `proxy_token` already needs a
    /// configure-push.  When set together with `ingest_token` (both
    /// non-empty), `state.ingest` is updated and subsequent
    /// `send_artefact` calls fire a fire-and-forget POST.  Empty or
    /// missing leaves the existing config alone — a re-push that
    /// only updates other fields shouldn't wipe ingest.
    #[serde(default)]
    ingest_url: Option<String>,
    /// Per-instance `it_<32hex>` bearer for the ingest endpoint.
    /// Mirrors `SWARM_INGEST_TOKEN`.  See `ingest_url` for posture.
    #[serde(default)]
    ingest_token: Option<String>,
    /// Full URL the swarm-mode background state worker POSTs selected
    /// workspace files to. Mirrors `SWARM_STATE_SYNC_URL`; pushed here
    /// because warmup env is frozen for the running dyson process.
    #[serde(default)]
    state_sync_url: Option<String>,
    /// Per-instance `st_<32hex>` bearer for the state-file endpoint.
    #[serde(default)]
    state_sync_token: Option<String>,
    /// Token-isolated Telegram proxy settings supplied by swarm.
    /// Patches/creates the Telegram controller in webhook mode.
    #[serde(default)]
    telegram_proxy: Option<TelegramProxyConfigure>,
}

#[derive(Debug, Deserialize)]
struct TelegramProxyConfigure {
    base_url: String,
    file_base_url: String,
    bearer: String,
    #[serde(default = "default_true")]
    enabled: bool,
}

fn default_true() -> bool {
    true
}

#[derive(Debug, Deserialize)]
struct RestoreStateFileBody {
    namespace: String,
    path: String,
    #[serde(default)]
    mime: Option<String>,
    #[serde(default)]
    deleted: bool,
    #[serde(default)]
    body_b64: Option<String>,
}

#[derive(Debug, Deserialize)]
struct InstallSkillAdminBody {
    marketplace: String,
    skill: String,
    #[serde(default)]
    force: bool,
    package: crate::tool::skill_marketplace::SkillBody,
}

async fn authorize_configure(headers: &hyper::HeaderMap, state: &HttpState) -> Option<Resp> {
    let secret = match headers
        .get(CONFIGURE_HEADER)
        .and_then(|v| v.to_str().ok())
        .map(str::trim)
        .filter(|s| !s.is_empty())
    {
        Some(s) => s.to_owned(),
        None => return Some(unauthorized(state)),
    };

    // Resolve the hash file's path.  Living next to `workspace/`
    // means a cube template restore picks it up via the writable
    // layer — same spot dyson_home resolves to from
    // `dyson swarm`'s DYSON_HOME env (default /var/lib/dyson).
    let snapshot = state.settings_snapshot();
    let hash_dir = workspace_parent_dir(snapshot.workspace.connection_string.expose());
    let hash_path = hash_dir.join(CONFIGURE_HASH_FILENAME);

    let _guard = CONFIGURE_AUTH_LOCK
        .get_or_init(|| tokio::sync::Mutex::new(()))
        .lock()
        .await;

    match tokio::fs::read_to_string(&hash_path).await {
        Ok(stored) => verify_configure_secret(&hash_path, secret, stored, state).await,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            let hash = match hash_configure_secret(secret.clone()).await {
                ConfigureHashOutcome::Hashed(hash) => hash,
                ConfigureHashOutcome::Failed(msg) => {
                    return Some(bad_request(&format!("argon2: {msg}")));
                }
            };
            if let Err(e) = tokio::fs::create_dir_all(&hash_dir).await {
                return Some(bad_request(&format!("mkdir {}: {e}", hash_dir.display())));
            }

            match tokio::fs::OpenOptions::new()
                .write(true)
                .create_new(true)
                .open(&hash_path)
                .await
            {
                Ok(mut file) => {
                    if let Err(e) = file.write_all(hash.as_bytes()).await {
                        return Some(bad_request(&format!("write {}: {e}", hash_path.display())));
                    }
                    #[cfg(unix)]
                    {
                        use std::os::unix::fs::PermissionsExt;
                        let _ = tokio::fs::set_permissions(
                            &hash_path,
                            std::fs::Permissions::from_mode(0o600),
                        )
                        .await;
                    }
                    remember_configure_verify(&hash_path, &secret, &hash);
                    None
                }
                Err(e) if e.kind() == std::io::ErrorKind::AlreadyExists => {
                    match tokio::fs::read_to_string(&hash_path).await {
                        Ok(stored) => {
                            verify_configure_secret(&hash_path, secret, stored, state).await
                        }
                        Err(e) => Some(bad_request(&format!("read {}: {e}", hash_path.display()))),
                    }
                }
                Err(e) => Some(bad_request(&format!("create {}: {e}", hash_path.display()))),
            }
        }
        Err(e) => Some(bad_request(&format!("read {}: {e}", hash_path.display()))),
    }
}

enum ConfigureHashOutcome {
    Hashed(String),
    Failed(String),
}

async fn hash_configure_secret(secret: String) -> ConfigureHashOutcome {
    tokio::task::spawn_blocking(move || {
        use argon2::Argon2;
        use argon2::password_hash::{PasswordHasher, SaltString, rand_core::OsRng};

        let salt = SaltString::generate(&mut OsRng);
        match Argon2::default().hash_password(secret.as_bytes(), &salt) {
            Ok(hash) => ConfigureHashOutcome::Hashed(hash.to_string()),
            Err(e) => ConfigureHashOutcome::Failed(e.to_string()),
        }
    })
    .await
    .unwrap_or_else(|e| ConfigureHashOutcome::Failed(format!("worker join failed: {e}")))
}

enum ConfigureVerifyOutcome {
    Verified,
    BadSecret,
    Unreadable(String),
}

async fn verify_configure_secret(
    hash_path: &Path,
    secret: String,
    stored: String,
    state: &HttpState,
) -> Option<Resp> {
    let stored = stored.trim().to_owned();
    if configure_verify_cache_hit(hash_path, &secret, &stored) {
        return None;
    }

    let secret_for_worker = secret.clone();
    let stored_for_worker = stored.clone();
    let outcome = tokio::task::spawn_blocking(move || {
        use argon2::Argon2;
        use argon2::password_hash::{PasswordHash, PasswordVerifier};

        let parsed = match PasswordHash::new(&stored_for_worker) {
            Ok(parsed) => parsed,
            Err(e) => return ConfigureVerifyOutcome::Unreadable(e.to_string()),
        };
        match Argon2::default().verify_password(secret_for_worker.as_bytes(), &parsed) {
            Ok(()) => ConfigureVerifyOutcome::Verified,
            Err(_) => ConfigureVerifyOutcome::BadSecret,
        }
    })
    .await
    .unwrap_or_else(|e| ConfigureVerifyOutcome::Unreadable(format!("worker join failed: {e}")));

    match outcome {
        ConfigureVerifyOutcome::Verified => {
            remember_configure_verify(hash_path, &secret, &stored);
            None
        }
        ConfigureVerifyOutcome::BadSecret => Some(unauthorized(state)),
        ConfigureVerifyOutcome::Unreadable(msg) => {
            Some(bad_request(&format!("stored hash unreadable: {msg}")))
        }
    }
}

fn configure_verify_cache_hit(hash_path: &Path, secret: &str, stored: &str) -> bool {
    let key = configure_verify_cache_key(hash_path, secret, stored);
    let now = Instant::now();
    let cache = CONFIGURE_VERIFY_CACHE.get_or_init(|| std::sync::Mutex::new(HashMap::new()));
    let mut guard = match cache.lock() {
        Ok(g) => g,
        Err(p) => p.into_inner(),
    };
    guard.retain(|_, expires_at| *expires_at > now);
    guard.get(&key).is_some_and(|expires_at| *expires_at > now)
}

fn remember_configure_verify(hash_path: &Path, secret: &str, stored: &str) {
    let key = configure_verify_cache_key(hash_path, secret, stored);
    let cache = CONFIGURE_VERIFY_CACHE.get_or_init(|| std::sync::Mutex::new(HashMap::new()));
    let mut guard = match cache.lock() {
        Ok(g) => g,
        Err(p) => p.into_inner(),
    };
    guard.insert(key, Instant::now() + CONFIGURE_VERIFY_CACHE_TTL);
}

fn configure_verify_cache_key(
    hash_path: &Path,
    secret: &str,
    stored: &str,
) -> ConfigureVerifyCacheKey {
    let mut secret_digest_prefix = [0_u8; 16];
    let secret_digest = Sha256::digest(secret.as_bytes());
    secret_digest_prefix.copy_from_slice(&secret_digest[..16]);

    let mut stored_digest_prefix = [0_u8; 16];
    let stored_digest = Sha256::digest(stored.as_bytes());
    stored_digest_prefix.copy_from_slice(&stored_digest[..16]);

    ConfigureVerifyCacheKey {
        hash_path: hash_path.to_path_buf(),
        secret_digest_prefix,
        stored_digest_prefix,
    }
}

fn json_status<T: Serialize>(status: StatusCode, v: &T) -> Resp {
    match serde_json::to_vec(v) {
        Ok(bytes) => Response::builder()
            .status(status)
            .header("Content-Type", "application/json")
            .body(boxed(Bytes::from(bytes)))
            .expect("status + content-type are valid"),
        Err(e) => bad_request(&format!("serialize: {e}")),
    }
}

pub(super) async fn post(req: Request<hyper::body::Incoming>, state: &HttpState) -> Resp {
    // Pull the configure secret BEFORE consuming the body — the
    // header check runs first so an unauthenticated caller can't
    // make us read a 64 KiB body just to reject it.
    if let Some(resp) = authorize_configure(req.headers(), state).await {
        return resp;
    }

    let body: ConfigureBody = match read_json_capped(req, MAX_CONFIGURE_BODY).await {
        Ok(b) => b,
        Err(e) => return bad_request(&e),
    };
    if body
        .task
        .as_deref()
        .is_some_and(looks_like_full_identity_doc)
    {
        return bad_request("task must be mission text; use identity_doc for full IDENTITY.md");
    }
    let snapshot = state.settings_snapshot();

    // 1. Workspace: rewrite IDENTITY.md from the new fields.  Empty
    //    fields are skipped (so a configure carrying only `models`
    //    won't blank the existing identity).
    let identity_changed = if body.name.is_some()
        || body.task.is_some()
        || body.instance_id.is_some()
        || body.identity_doc.is_some()
    {
        let mut ws = match crate::workspace::create_workspace(&snapshot.workspace) {
            Ok(w) => w,
            Err(e) => return bad_request(&format!("workspace open failed: {e}")),
        };
        if let Some(identity_doc) = body.identity_doc.as_deref() {
            if !looks_like_full_identity_doc(identity_doc) {
                return bad_request("identity_doc must be a full IDENTITY.md document");
            }
            ws.set("IDENTITY.md", identity_doc);
        } else {
            // Merge: keep the existing IDENTITY.md fields when the new
            // body omits them, so a partial update doesn't wipe identity.
            // Extract first into owned Strings so the merge doesn't dangle
            // references to temporaries.
            let existing = ws.get("IDENTITY.md").unwrap_or_default();
            let prior_name = extract_field(&existing, "Name");
            let prior_instance = extract_field(&existing, "Swarm instance id");
            let prior_mission = extract_section(&existing, "Mission")
                .or_else(|| looks_like_full_identity_doc(&existing).then(|| existing.clone()));
            let merged = build_identity_md(
                body.name.as_deref().or(prior_name.as_deref()),
                body.instance_id.as_deref().or(prior_instance.as_deref()),
                body.task.as_deref().or(prior_mission.as_deref()),
            );
            ws.set("IDENTITY.md", &merged);
        }
        if let Err(e) = ws.save() {
            return bad_request(&format!("workspace save failed: {e}"));
        }
        true
    } else {
        false
    };

    // 2. dyson.json: patch the agent provider's `models`, `api_key`,
    //    and/or `base_url` if the body supplies them.  All three
    //    targets share the same patch helper because the surface is
    //    a single `providers.<agent.provider>` object — one
    //    read-modify-write keeps the file in a consistent state and
    //    the HotReloader fires once per change cluster instead of
    //    three times.  Empty / None on a field means "leave alone".
    let config_path = state.config_path();
    let has_config = config_path.is_some();
    let want_models = !body.models.is_empty();
    let want_api_key = has_text(body.proxy_token.as_deref());
    let want_base_url = has_text(body.proxy_base.as_deref());
    let provider_requested = want_models || want_api_key || want_base_url;
    let provider_applied = provider_requested && has_config;
    let models_applied = want_models && provider_applied;

    // 3. Image generation: register / replace the dedicated image
    //    provider block and point `agent.image_generation_*` at it.
    //    Independent of the chat patch above — the chat path's
    //    `agent.provider` is `openrouter` (LlmProvider::OpenAi under
    //    the hood) but the image factory dispatches on real
    //    LlmProvider variants, so the two need separate provider
    //    entries.  Existing dysons (created before this field was
    //    plumbed) get retroactively rewired by the swarm-side sweep
    //    that pushes a configure with these set.
    let want_image_block =
        has_text(body.image_provider_name.as_deref()) && body.image_provider_block.is_some();
    let want_image_provider = has_text(body.image_generation_provider.as_deref());
    let want_image_model = has_text(body.image_generation_model.as_deref());
    let image_requested = want_image_block || want_image_provider || want_image_model;
    let image_applied = image_requested && has_config;
    // 4. Skills: an explicit `tools` list rewrites
    //    `skills.builtin.tools` to that exact set; otherwise
    //    `reset_skills` drops the `skills` key so the loader's
    //    defaults path registers every builtin.  Independent of the
    //    chat / image patches — swarm's sweep flips one of these on
    //    every push so toolless instances self-heal on the next
    //    configure.  `tools` wins if both are set.
    let skills_requested = body.tools.is_some() || body.reset_skills;
    let skills_applied = skills_requested && has_config;

    // 5. MCP servers: replace the top-level `mcp_servers` block.  None
    //    leaves it alone; an empty map clears it.  Distinct from the
    //    skills block because MCP servers are a sibling key in the
    //    loader's `JsonRoot`, not nested under `skills`.
    let mcp_applied = body.mcp_servers.is_some() && has_config;
    let telegram_applied = body.telegram_proxy.is_some() && has_config;

    let config_patch = if let Some(path) = config_path {
        match patch_config_once(
            path,
            ConfigureConfigPatch {
                models: if want_models {
                    Some(body.models.as_slice())
                } else {
                    None
                },
                api_key: if want_api_key {
                    body.proxy_token.as_deref()
                } else {
                    None
                },
                base_url: if want_base_url {
                    body.proxy_base.as_deref()
                } else {
                    None
                },
                image_provider_block: if want_image_block {
                    body.image_provider_name
                        .as_deref()
                        .zip(body.image_provider_block.as_ref())
                } else {
                    None
                },
                image_provider: if want_image_provider {
                    body.image_generation_provider.as_deref()
                } else {
                    None
                },
                image_model: if want_image_model {
                    body.image_generation_model.as_deref()
                } else {
                    None
                },
                tools: body.tools.as_deref(),
                reset_skills: body.reset_skills,
                mcp_servers: body.mcp_servers.as_ref(),
                telegram_proxy: body.telegram_proxy.as_ref(),
            },
        )
        .await
        {
            Ok(patch) => patch,
            Err(e) => return bad_request(&format!("config patch failed: {e}")),
        }
    } else {
        AppliedConfigPatch::default()
    };
    let provider_changed = config_patch.provider_changed;
    let models_changed = provider_changed && want_models;
    let image_changed = config_patch.image_changed;
    let skills_changed = config_patch.skills_changed;
    let mcp_changed = config_patch.mcp_changed;
    let telegram_changed = config_patch.telegram_changed;

    let any_config_changed =
        provider_changed || image_changed || skills_changed || mcp_changed || telegram_changed;

    let agent_secrets_patch =
        agent_secrets_runtime_patch(&body.proxy_base, &body.proxy_token, &body.instance_id);
    let agent_secrets_applied = agent_secrets_patch.is_some();
    let agent_secrets_changed = match &agent_secrets_patch {
        Some(AgentSecretsRuntimePatch::Set {
            proxy_url,
            proxy_token,
            instance_id,
        }) => {
            crate::tool::agent_secrets::set_runtime_config_from_parts(
                proxy_url,
                proxy_token,
                instance_id,
            );
            crate::swarm_cost::set_runtime_config_from_parts(proxy_url, proxy_token);
            true
        }
        Some(AgentSecretsRuntimePatch::Clear) => {
            crate::tool::agent_secrets::set_runtime_config(None);
            crate::swarm_cost::set_runtime_config(None);
            true
        }
        _ => false,
    };

    // Eagerly reload the settings + ClientRegistry instead of waiting
    // for the 2s polling HotReloader to notice the mtime change.  Two
    // reasons this matters:
    //   1. Cube snapshot/restore freezes the dyson process — there's
    //      a real possibility the program-level hot-reload tokio task
    //      doesn't survive the resume cleanly, leaving the registry
    //      pinned to its warmup-time clients (api_key
    //      "warmup-placeholder", base_url api.openai.com).  The chat
    //      then 401s against api.openai.com on every turn.
    //   2. Even when the polling loop IS alive, a chat that fires
    //      between the patch and the next 2s tick caches the warmup
    //      client; the per-chat HotReloader's baseline is then
    //      post-patch, so subsequent turns see no change and never
    //      rebuild.  Eager reload closes the window entirely.
    if any_config_changed && let Some(path) = config_path {
        let path = path.to_path_buf();
        match tokio::task::spawn_blocking(move || crate::config::loader::load_settings(Some(&path)))
            .await
        {
            Ok(Ok(mut new_settings)) => {
                preserve_runtime_only_settings(&mut new_settings, &snapshot);
                state.registry.reload(&new_settings, None);
                if let Ok(mut g) = state.settings.write() {
                    *g = new_settings.clone();
                }
                crate::controller::publish_settings(std::sync::Arc::new(new_settings));
                tracing::info!("dyson.json patched + registry reloaded by /api/admin/configure");
            }
            Ok(Err(e)) => {
                tracing::warn!(
                    error = %e,
                    "post-patch settings reload failed; falling back to polling HotReloader"
                );
            }
            Err(e) => {
                tracing::warn!(
                    error = %e,
                    "post-patch settings reload worker failed; falling back to polling HotReloader"
                );
            }
        }
    }

    // Patch the runtime artefact-ingest target.  Both fields must be
    // non-empty in the same body to take effect — a partial body
    // (just `ingest_url` without a token) leaves the existing config
    // alone rather than landing a half-broken target.  Same posture
    // as the proxy_token / proxy_base patch: mutating in place keeps
    // a running `SseOutput` reading the live values without an
    // agent rebuild.  Both empty strings → clear the config (operator
    // turned ingest off explicitly).
    let ingest_patch = runtime_patch(&body.ingest_url, &body.ingest_token);
    let ingest_applied = ingest_patch.is_some();
    let ingest_changed = match &ingest_patch {
        Some(RuntimePatch::Set { url, token }) => {
            let cfg = super::super::state::IngestConfig {
                url: url.to_string(),
                token: token.to_string(),
            };
            if let Ok(mut g) = state.ingest.lock() {
                *g = Some(cfg);
            }
            true
        }
        Some(RuntimePatch::Clear) => {
            if let Ok(mut g) = state.ingest.lock() {
                *g = None;
            }
            true
        }
        _ => false,
    };
    let state_sync_patch = runtime_patch(&body.state_sync_url, &body.state_sync_token);
    let state_sync_applied = state_sync_patch.is_some();
    let state_sync_changed = match &state_sync_patch {
        Some(RuntimePatch::Set { url, token }) => {
            crate::swarm_state_sync::set_config(Some(crate::swarm_state_sync::StateSyncConfig {
                url: url.to_string(),
                token: token.to_string(),
            }));
            true
        }
        Some(RuntimePatch::Clear) => {
            crate::swarm_state_sync::set_config(None);
            true
        }
        _ => false,
    };
    json_ok(&serde_json::json!({
        "ok": true,
        "identity_updated": identity_changed,
        "models_updated": models_changed,
        "models_applied": models_applied,
        "provider_updated": provider_changed,
        "provider_applied": provider_applied,
        "image_generation_updated": image_changed,
        "image_generation_applied": image_applied,
        "skills_reset": skills_changed,
        "skills_applied": skills_applied,
        "mcp_servers_updated": mcp_changed,
        "mcp_servers_applied": mcp_applied,
        "telegram_updated": telegram_changed,
        "telegram_applied": telegram_applied,
        "ingest_updated": ingest_changed,
        "ingest_applied": ingest_applied,
        "state_sync_updated": state_sync_changed,
        "state_sync_applied": state_sync_applied,
        "agent_secrets_updated": agent_secrets_changed,
        "agent_secrets_applied": agent_secrets_applied,
    }))
}

fn preserve_runtime_only_settings(new_settings: &mut Settings, snapshot: &Settings) {
    // `dangerous_no_sandbox` is deliberately CLI-only and never serialized
    // into dyson.json. Eager runtime reloads must carry it forward or swarm
    // instances inside Cube will try to build an OS sandbox and exit because
    // bwrap is not installed there.
    new_settings.dangerous_no_sandbox = snapshot.dangerous_no_sandbox;
}

#[derive(Debug, PartialEq, Eq)]
enum RuntimePatch<'a> {
    Set { url: &'a str, token: &'a str },
    Clear,
}

#[derive(Debug, PartialEq, Eq)]
enum AgentSecretsRuntimePatch<'a> {
    Set {
        proxy_url: &'a str,
        proxy_token: &'a str,
        instance_id: &'a str,
    },
    Clear,
}

fn has_text(value: Option<&str>) -> bool {
    value.is_some_and(|s| !s.is_empty())
}

fn runtime_patch<'a>(
    url: &'a Option<String>,
    token: &'a Option<String>,
) -> Option<RuntimePatch<'a>> {
    match (url.as_deref(), token.as_deref()) {
        (Some(url), Some(token)) if !url.is_empty() && !token.is_empty() => {
            Some(RuntimePatch::Set { url, token })
        }
        (Some(""), Some("")) => Some(RuntimePatch::Clear),
        _ => None,
    }
}

fn agent_secrets_runtime_patch<'a>(
    proxy_url: &'a Option<String>,
    proxy_token: &'a Option<String>,
    instance_id: &'a Option<String>,
) -> Option<AgentSecretsRuntimePatch<'a>> {
    match (
        proxy_url.as_deref(),
        proxy_token.as_deref(),
        instance_id.as_deref(),
    ) {
        (Some(proxy_url), Some(proxy_token), Some(instance_id))
            if !proxy_url.is_empty() && !proxy_token.is_empty() && !instance_id.is_empty() =>
        {
            Some(AgentSecretsRuntimePatch::Set {
                proxy_url,
                proxy_token,
                instance_id,
            })
        }
        (Some(""), Some(""), Some("")) => Some(AgentSecretsRuntimePatch::Clear),
        _ => None,
    }
}

pub(super) async fn post_state_file(
    req: Request<hyper::body::Incoming>,
    state: &HttpState,
) -> Resp {
    if let Some(resp) = authorize_configure(req.headers(), state).await {
        return resp;
    }
    let body: RestoreStateFileBody = match read_json_capped(req, MAX_STATE_FILE_BODY).await {
        Ok(b) => b,
        Err(e) => return bad_request(&e),
    };
    let snapshot = state.settings_snapshot();
    let root = match state_root(&snapshot, &body.namespace) {
        Ok(root) => root,
        Err(e) => return bad_request(&e),
    };
    let rel = match clean_relative_path(&body.path) {
        Ok(path) => path,
        Err(e) => return bad_request(&e),
    };
    let rel_path = rel
        .components()
        .filter_map(|c| match c {
            Component::Normal(s) => s.to_str(),
            _ => None,
        })
        .collect::<Vec<_>>()
        .join("/");
    if !crate::swarm_state_sync::is_durable_state_file_path(&body.namespace, &rel_path) {
        return bad_request("state file path is not durable state");
    }
    let abs = root.join(&rel);

    if body.deleted {
        match tokio::fs::remove_file(&abs).await {
            Ok(()) => {}
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
            Err(e) => return bad_request(&format!("remove {}: {e}", abs.display())),
        }
        return json_ok(&serde_json::json!({
            "ok": true,
            "namespace": body.namespace,
            "path": body.path,
            "deleted": true,
        }));
    }

    let Some(encoded) = body.body_b64.as_deref() else {
        return bad_request("body_b64 is required unless deleted=true");
    };
    let bytes = match B64.decode(encoded) {
        Ok(bytes) => bytes,
        Err(e) => return bad_request(&format!("body_b64 decode: {e}")),
    };
    if bytes.len() > 5 * 1024 * 1024 {
        return bad_request("state file exceeds 5 MiB");
    }
    if crate::swarm_state_sync::is_zero_byte_chat_transcript(
        &body.namespace,
        &rel_path,
        bytes.len() as u64,
    ) {
        return bad_request("zero-byte chat transcripts are not durable state");
    }
    if let Some(parent) = abs.parent()
        && let Err(e) = tokio::fs::create_dir_all(parent).await
    {
        return bad_request(&format!("mkdir {}: {e}", parent.display()));
    }
    let tmp = abs.with_extension("dyson-state-restore.tmp");
    if let Err(e) = tokio::fs::write(&tmp, &bytes).await {
        return bad_request(&format!("write {}: {e}", tmp.display()));
    }
    if let Err(e) = tokio::fs::rename(&tmp, &abs).await {
        let _ = tokio::fs::remove_file(&tmp).await;
        return bad_request(&format!(
            "rename {} -> {}: {e}",
            tmp.display(),
            abs.display()
        ));
    }
    state.observe_replayed_state_file(&body.namespace, &rel_path);
    json_ok(&serde_json::json!({
        "ok": true,
        "namespace": body.namespace,
        "path": body.path,
        "mime": body.mime,
        "bytes": bytes.len(),
        "deleted": false,
    }))
}

pub(super) async fn post_skill_install(
    req: Request<hyper::body::Incoming>,
    state: &HttpState,
) -> Resp {
    if let Some(resp) = authorize_configure(req.headers(), state).await {
        return resp;
    }
    let body: InstallSkillAdminBody = match read_json_capped(req, MAX_SKILL_INSTALL_BODY).await {
        Ok(b) => b,
        Err(e) => return bad_request(&e),
    };
    let snapshot = state.settings_snapshot();
    let workspace = match crate::workspace::create_workspace(&snapshot.workspace) {
        Ok(w) => Arc::new(RwLock::new(w)),
        Err(e) => return bad_request(&format!("workspace open failed: {e}")),
    };
    match crate::tool::skill_marketplace::install_skill_package_to_workspace(
        &workspace,
        body.marketplace.trim(),
        body.skill.trim(),
        body.package,
        body.force,
    )
    .await
    {
        Ok(outcome) => json_ok(&outcome),
        Err(crate::tool::skill_marketplace::SkillInstallError::AlreadyInstalled {
            current_version,
        }) => json_status(
            StatusCode::CONFLICT,
            &serde_json::json!({
                "error": "already_installed",
                "current_version": current_version,
            }),
        ),
        Err(crate::tool::skill_marketplace::SkillInstallError::Invalid(msg)) => bad_request(&msg),
        Err(crate::tool::skill_marketplace::SkillInstallError::Workspace(err)) => {
            bad_request(&format!("workspace install failed: {err}"))
        }
    }
}

pub(super) async fn delete_skill(
    req: Request<hyper::body::Incoming>,
    state: &HttpState,
    skill: &str,
) -> Resp {
    if let Some(resp) = authorize_configure(req.headers(), state).await {
        return resp;
    }
    let snapshot = state.settings_snapshot();
    let workspace = match crate::workspace::create_workspace(&snapshot.workspace) {
        Ok(w) => Arc::new(RwLock::new(w)),
        Err(e) => return bad_request(&format!("workspace open failed: {e}")),
    };
    match crate::tool::skill_marketplace::remove_skill_from_workspace(&workspace, skill.trim())
        .await
    {
        Ok(outcome) => json_ok(&outcome),
        Err(crate::tool::skill_marketplace::SkillRemoveError::Invalid(msg)) => bad_request(&msg),
        Err(crate::tool::skill_marketplace::SkillRemoveError::NotInstalled) => json_status(
            StatusCode::NOT_FOUND,
            &serde_json::json!({
                "error": "skill_not_installed",
                "skill": skill,
            }),
        ),
        Err(crate::tool::skill_marketplace::SkillRemoveError::Workspace(err)) => {
            bad_request(&format!("workspace uninstall failed: {err}"))
        }
    }
}

pub(super) async fn get_idle(req: Request<hyper::body::Incoming>, state: &HttpState) -> Resp {
    if let Some(resp) = authorize_configure(req.headers(), state).await {
        return resp;
    }
    let in_flight = state.in_flight_chats().await;
    json_ok(&serde_json::json!({
        "ok": true,
        "idle": in_flight == 0,
        "in_flight_chats": in_flight,
        "quiesced": state.is_quiesced(),
    }))
}

pub(super) async fn post_quiesce(req: Request<hyper::body::Incoming>, state: &HttpState) -> Resp {
    if let Some(resp) = authorize_configure(req.headers(), state).await {
        return resp;
    }
    let in_flight = state.try_quiesce().await;
    if in_flight != 0 {
        let body = serde_json::json!({
            "ok": false,
            "idle": false,
            "in_flight_chats": in_flight,
            "quiesced": false,
        })
        .to_string();
        return Response::builder()
            .status(StatusCode::CONFLICT)
            .header("Content-Type", "application/json")
            .body(boxed(Bytes::from(body)))
            .unwrap();
    }
    json_ok(&serde_json::json!({
        "ok": true,
        "idle": true,
        "in_flight_chats": 0,
        "quiesced": true,
    }))
}

pub(super) async fn post_unquiesce(req: Request<hyper::body::Incoming>, state: &HttpState) -> Resp {
    if let Some(resp) = authorize_configure(req.headers(), state).await {
        return resp;
    }
    state.unquiesce();
    json_ok(&serde_json::json!({
        "ok": true,
        "quiesced": false,
    }))
}

fn state_root(
    settings: &crate::config::Settings,
    namespace: &str,
) -> std::result::Result<PathBuf, String> {
    match namespace {
        "workspace" => Ok(crate::util::resolve_tilde(
            settings.workspace.connection_string.expose(),
        )),
        "chats" => Ok(crate::util::resolve_tilde(
            settings.chat_history.connection_string.expose(),
        )),
        _ => Err(format!("unsupported namespace {namespace:?}")),
    }
}

fn clean_relative_path(path: &str) -> std::result::Result<PathBuf, String> {
    if path.is_empty() || path.len() > 2048 || path.contains('\0') {
        return Err("bad path length or nul byte".into());
    }
    if path.starts_with('/') || path.contains('\\') {
        return Err("paths must be relative and slash-separated".into());
    }
    let p = Path::new(path);
    let mut out = PathBuf::new();
    for component in p.components() {
        match component {
            Component::Normal(part) if !part.is_empty() => out.push(part),
            _ => return Err("paths must be clean relative paths".into()),
        }
    }
    if out.as_os_str().is_empty() {
        return Err("path is empty".into());
    }
    Ok(out)
}

/// Diagnostic: return the live skill / tool inventory so an operator
/// can confirm which MCP servers actually loaded after a configure
/// push.  Same configure-secret auth as `post()` (the only auth
/// surface on `/api/admin/*`).  Builds a throwaway agent off the
/// current settings so we report the actual `on_load` outcome — a
/// live `state.registry` only caches LLM clients, not skills.
pub(super) async fn get_skills(req: Request<hyper::body::Incoming>, state: &HttpState) -> Resp {
    use crate::skill::Skill;

    if let Some(resp) = authorize_configure(req.headers(), state).await {
        return resp;
    }

    // Re-load settings fresh from disk — this is the same path
    // build_agent uses, so the result reflects what an actual chat
    // turn would build with.
    let path = match state.config_path() {
        Some(p) => p.to_path_buf(),
        None => return bad_request("config_path is not set"),
    };
    let settings = match crate::config::loader::load_settings(Some(&path)) {
        Ok(s) => s,
        Err(e) => return bad_request(&format!("load_settings: {e}")),
    };

    let mut by_kind: Vec<serde_json::Value> = Vec::new();
    let mut mcp_listed: Vec<serde_json::Value> = Vec::new();
    for sk in &settings.skills {
        match sk {
            crate::config::SkillConfig::Builtin(b) => {
                by_kind.push(serde_json::json!({
                    "kind": "builtin",
                    "tools_filter": b.tools.len(),
                }));
            }
            crate::config::SkillConfig::Local(l) => {
                by_kind.push(serde_json::json!({
                    "kind": "local",
                    "name": l.name,
                    "path": l.path,
                }));
            }
            crate::config::SkillConfig::Subagent(sa) => {
                by_kind.push(serde_json::json!({
                    "kind": "subagent",
                    "agents": sa.agents.iter().map(|a| a.name.clone()).collect::<Vec<_>>(),
                }));
            }
            crate::config::SkillConfig::Mcp(m) => {
                let transport = match &m.transport {
                    crate::config::McpTransportConfig::Http { url, headers, auth } => {
                        serde_json::json!({
                            "type": "http",
                            "url": url,
                            "header_keys": headers.keys().collect::<Vec<_>>(),
                            "oauth": auth.is_some(),
                        })
                    }
                    crate::config::McpTransportConfig::Stdio { command, .. } => {
                        serde_json::json!({ "type": "stdio", "command": command })
                    }
                };
                mcp_listed.push(serde_json::json!({
                    "name": m.name,
                    "transport": transport,
                }));
            }
        }
    }

    // Try to actually load each MCP skill so we can report the
    // on_load outcome — handshake errors (the silent-skip path in
    // skill::build_skills) surface here as `loaded: false` with the
    // captured error string.  Doesn't share state with running
    // chats; just a probe.
    let mut mcp_probes: Vec<serde_json::Value> = Vec::new();
    for sk in &settings.skills {
        if let crate::config::SkillConfig::Mcp(cfg) = sk {
            let mut skill = crate::skill::mcp::McpSkill::new(*cfg.clone());
            let result = skill.on_load().await;
            mcp_probes.push(match result {
                Ok(()) => serde_json::json!({
                    "name": cfg.name,
                    "loaded": true,
                    "tools": skill.tools().len(),
                    "tool_names": skill.tools().iter().map(|t| t.name().to_string()).collect::<Vec<_>>(),
                }),
                Err(e) => serde_json::json!({
                    "name": cfg.name,
                    "loaded": false,
                    "error": e.to_string(),
                }),
            });
        }
    }

    json_ok(&serde_json::json!({
        "ok": true,
        "skills": by_kind,
        "mcp_servers": mcp_listed,
        "mcp_probes": mcp_probes,
    }))
}

#[derive(Debug, Default, Deserialize)]
pub(super) struct CostBackfillBody {
    #[serde(default)]
    dry_run: bool,
}

/// Fleet operation hook used by swarmctl after Dyson rollouts.
///
/// This route is still protected by the controller's normal `/api/*` bearer
/// gate and CSRF header. It intentionally does not require the configure
/// secret because swarmctl discovers live instances from Swarm's DB and calls
/// them with their per-instance bearer token.
pub(super) async fn post_cost_backfill(
    req: Request<hyper::body::Incoming>,
    state: &HttpState,
) -> Resp {
    let body: CostBackfillBody = match read_json_capped(req, MAX_COST_BACKFILL_BODY).await {
        Ok(body) => body,
        Err(err) => return bad_request(&err),
    };
    let Some(history) = state.history.as_ref() else {
        return bad_request("chat history backend is not configured");
    };
    let Some(costs) = crate::swarm_cost::config_snapshot_or_env() else {
        return Response::builder()
            .status(StatusCode::SERVICE_UNAVAILABLE)
            .header("Content-Type", "application/json")
            .body(boxed(Bytes::from(
                serde_json::json!({
                    "ok": false,
                    "error": "Swarm cost lookup is not configured"
                })
                .to_string(),
            )))
            .unwrap();
    };
    match crate::message_cost_backfill::backfill_history(
        history.as_ref(),
        &costs,
        crate::message_cost_backfill::CostBackfillOptions {
            dry_run: body.dry_run,
        },
    )
    .await
    {
        Ok(report) => json_ok(&serde_json::json!({
            "ok": true,
            "dry_run": body.dry_run,
            "messages_scanned": report.messages_scanned,
            "messages_linked": report.messages_linked,
            "messages_priced": report.messages_priced,
            "messages_skipped": report.messages_skipped,
            "skip_reasons": report.skip_reasons,
        })),
        Err(err) => {
            tracing::warn!(error = %err, "cost backfill failed");
            Response::builder()
                .status(StatusCode::INTERNAL_SERVER_ERROR)
                .header("Content-Type", "application/json")
                .body(boxed(Bytes::from(
                    serde_json::json!({
                        "ok": false,
                        "error": "cost backfill failed"
                    })
                    .to_string(),
                )))
                .unwrap()
        }
    }
}

/// Resolve the directory the configure-secret hash lives in.  We
/// keep it next to the workspace so cube template restores preserve
/// it via the writable layer.  `connection_string` for the in-memory
/// workspace is its directory path; for the file-backed default
/// it's the directory directly.  For unknown shapes we fall back to
/// `/var/lib/dyson` which matches `dyson swarm`'s default home.
fn workspace_parent_dir(connection_string: &str) -> std::path::PathBuf {
    let p = std::path::PathBuf::from(connection_string);
    if let Some(parent) = p.parent().filter(|p| !p.as_os_str().is_empty()) {
        parent.to_path_buf()
    } else {
        std::path::PathBuf::from("/var/lib/dyson")
    }
}

/// Render the IDENTITY.md body in the same shape `dyson swarm` writes
/// at boot.  `Workspace::system_prompt()` injects the file under the
/// `## IDENTITY` section of the agent's system prompt, so the format
/// here is read by the model on every turn.
fn build_identity_md(
    name: Option<&str>,
    instance_id: Option<&str>,
    mission: Option<&str>,
) -> String {
    if let Some(m) = mission.filter(|s| looks_like_full_identity_doc(s)) {
        return m.to_owned();
    }
    let mut body = String::from("# Identity\n\n");
    if let Some(n) = name.filter(|s| !s.is_empty()) {
        body.push_str(&format!("Name: {n}\n"));
    }
    if let Some(id) = instance_id.filter(|s| !s.is_empty()) {
        body.push_str(&format!("Swarm instance id: {id}\n"));
    }
    if let Some(m) = mission.filter(|s| !s.is_empty()) {
        body.push_str(&format!("\n## Mission\n\n{m}\n"));
    }
    body
}

fn looks_like_full_identity_doc(body: &str) -> bool {
    let trimmed = body.trim_start();
    trimmed.starts_with("# IDENTITY.md") || trimmed.starts_with("# Identity")
}

/// Crude `Key: value` line scanner — good enough for the two top-of-file
/// fields IDENTITY.md uses.  Returns the trimmed value or None.
fn extract_field(body: &str, key: &str) -> Option<String> {
    let prefix = format!("{key}:");
    body.lines()
        .find_map(|l| l.strip_prefix(&prefix))
        .map(|s| s.trim().to_owned())
        .filter(|s| !s.is_empty())
}

/// Pull the body of a `## <name>` section up to the next `##` heading
/// or end of file.  Used to preserve existing mission text when a
/// configure carries only `name` / `instance_id`.
fn extract_section(body: &str, name: &str) -> Option<String> {
    let header = format!("## {name}");
    let mut found = false;
    let mut out = String::new();
    for line in body.lines() {
        if found {
            if line.starts_with("## ") {
                break;
            }
            out.push_str(line);
            out.push('\n');
        } else if line.trim() == header {
            found = true;
        }
    }
    let trimmed = out.trim().to_owned();
    if trimmed.is_empty() {
        None
    } else {
        Some(trimmed)
    }
}

struct ConfigureConfigPatch<'a> {
    models: Option<&'a [String]>,
    api_key: Option<&'a str>,
    base_url: Option<&'a str>,
    image_provider_block: Option<(&'a str, &'a Value)>,
    image_provider: Option<&'a str>,
    image_model: Option<&'a str>,
    tools: Option<&'a [String]>,
    reset_skills: bool,
    mcp_servers: Option<&'a serde_json::Map<String, Value>>,
    telegram_proxy: Option<&'a TelegramProxyConfigure>,
}

#[derive(Default)]
struct AppliedConfigPatch {
    provider_changed: bool,
    image_changed: bool,
    skills_changed: bool,
    mcp_changed: bool,
    telegram_changed: bool,
}

impl AppliedConfigPatch {
    fn any(&self) -> bool {
        self.provider_changed
            || self.image_changed
            || self.skills_changed
            || self.mcp_changed
            || self.telegram_changed
    }
}

#[derive(Debug, thiserror::Error)]
enum ConfigureConfigPatchError {
    #[error("read {path}: {source}")]
    Read {
        path: PathBuf,
        source: std::io::Error,
    },
    #[error("parse {path}: {source}")]
    Parse {
        path: PathBuf,
        source: serde_json::Error,
    },
    #[error("config root is not an object")]
    RootNotObject,
    #[error("config has no agent.provider - can't tell which provider's config to patch")]
    MissingAgentProvider,
    #[error("config has no providers object")]
    MissingProvidersObject,
    #[error("config has no providers.{0}")]
    MissingProvider(String),
    #[error("config providers is not an object")]
    ProvidersNotObject,
    #[error("config agent is not an object")]
    AgentNotObject,
    #[error("skills is not an object")]
    SkillsNotObject,
    #[error("skills.builtin is not an object")]
    SkillsBuiltinNotObject,
    #[error("serialise: {0}")]
    Serialize(serde_json::Error),
    #[error("write tmp: {0}")]
    WriteTmp(std::io::Error),
    #[error("rename: {0}")]
    Rename(std::io::Error),
}

async fn patch_config_once(
    path: &std::path::Path,
    patch: ConfigureConfigPatch<'_>,
) -> std::result::Result<AppliedConfigPatch, ConfigureConfigPatchError> {
    let raw = tokio::fs::read_to_string(path).await.map_err(|source| {
        ConfigureConfigPatchError::Read {
            path: path.to_path_buf(),
            source,
        }
    })?;
    let mut doc: Value =
        serde_json::from_str(&raw).map_err(|source| ConfigureConfigPatchError::Parse {
            path: path.to_path_buf(),
            source,
        })?;
    let mut applied = AppliedConfigPatch::default();

    if patch.models.is_some() || patch.api_key.is_some() || patch.base_url.is_some() {
        patch_provider_doc(&mut doc, patch.models, patch.api_key, patch.base_url)?;
        applied.provider_changed = true;
    }
    if patch.image_provider_block.is_some()
        || patch.image_provider.is_some()
        || patch.image_model.is_some()
    {
        patch_image_generation_doc(
            &mut doc,
            patch.image_provider_block,
            patch.image_provider,
            patch.image_model,
        )?;
        applied.image_changed = true;
    }
    if let Some(tools) = patch.tools {
        applied.skills_changed = set_skills_tools_doc(&mut doc, tools)?;
    } else if patch.reset_skills {
        applied.skills_changed = clear_skills_doc(&mut doc)?;
    }
    if let Some(servers) = patch.mcp_servers {
        applied.mcp_changed = patch_mcp_servers_doc(&mut doc, servers)?;
    }
    if let Some(proxy) = patch.telegram_proxy {
        applied.telegram_changed = patch_telegram_controller_doc(&mut doc, proxy)?;
    }

    if applied.any() {
        write_config_doc(path, &doc).await?;
    }
    Ok(applied)
}

fn patch_provider_doc(
    doc: &mut Value,
    models: Option<&[String]>,
    api_key: Option<&str>,
    base_url: Option<&str>,
) -> std::result::Result<(), ConfigureConfigPatchError> {
    let provider_name = doc
        .get("agent")
        .and_then(|a| a.get("provider"))
        .and_then(|p| p.as_str())
        .ok_or(ConfigureConfigPatchError::MissingAgentProvider)?
        .to_owned();
    let primary_model = models.and_then(|ms| ms.first().filter(|m| !m.trim().is_empty()).cloned());
    if let Some(primary) = primary_model.as_ref() {
        let agent = doc
            .as_object_mut()
            .ok_or(ConfigureConfigPatchError::RootNotObject)?
            .entry("agent".to_string())
            .or_insert_with(|| Value::Object(serde_json::Map::new()))
            .as_object_mut()
            .ok_or(ConfigureConfigPatchError::AgentNotObject)?;
        agent.insert("model".into(), Value::String(primary.clone()));
    }

    let providers = doc
        .get_mut("providers")
        .and_then(|p| p.as_object_mut())
        .ok_or(ConfigureConfigPatchError::MissingProvidersObject)?;
    let prov_entry = providers
        .get_mut(&provider_name)
        .and_then(|p| p.as_object_mut())
        .ok_or_else(|| ConfigureConfigPatchError::MissingProvider(provider_name.clone()))?;
    if let Some(ms) = models {
        prov_entry.insert(
            "models".into(),
            Value::Array(ms.iter().map(|m| Value::String(m.clone())).collect()),
        );
    }
    if let Some(k) = api_key {
        prov_entry.insert("api_key".into(), Value::String(k.to_owned()));
    }
    if let Some(u) = base_url {
        prov_entry.insert("base_url".into(), Value::String(u.to_owned()));
    }
    Ok(())
}

fn patch_image_generation_doc(
    doc: &mut Value,
    provider_block: Option<(&str, &Value)>,
    image_provider: Option<&str>,
    image_model: Option<&str>,
) -> std::result::Result<(), ConfigureConfigPatchError> {
    if let Some((name, block)) = provider_block {
        let providers = doc
            .as_object_mut()
            .ok_or(ConfigureConfigPatchError::RootNotObject)?
            .entry("providers".to_string())
            .or_insert_with(|| Value::Object(serde_json::Map::new()))
            .as_object_mut()
            .ok_or(ConfigureConfigPatchError::ProvidersNotObject)?;
        providers.insert(name.to_owned(), block.clone());
    }

    if image_provider.is_some() || image_model.is_some() {
        let agent = doc
            .as_object_mut()
            .ok_or(ConfigureConfigPatchError::RootNotObject)?
            .entry("agent".to_string())
            .or_insert_with(|| Value::Object(serde_json::Map::new()))
            .as_object_mut()
            .ok_or(ConfigureConfigPatchError::AgentNotObject)?;
        if let Some(p) = image_provider {
            agent.insert(
                "image_generation_provider".into(),
                Value::String(p.to_owned()),
            );
        }
        if let Some(m) = image_model {
            agent.insert("image_generation_model".into(), Value::String(m.to_owned()));
        }
    }
    Ok(())
}

fn clear_skills_doc(doc: &mut Value) -> std::result::Result<bool, ConfigureConfigPatchError> {
    Ok(doc
        .as_object_mut()
        .ok_or(ConfigureConfigPatchError::RootNotObject)?
        .remove("skills")
        .is_some())
}

fn set_skills_tools_doc(
    doc: &mut Value,
    tools: &[String],
) -> std::result::Result<bool, ConfigureConfigPatchError> {
    let root = doc
        .as_object_mut()
        .ok_or(ConfigureConfigPatchError::RootNotObject)?;
    let new_tools = Value::Array(tools.iter().map(|t| Value::String(t.clone())).collect());
    let skills = root
        .entry("skills".to_string())
        .or_insert_with(|| Value::Object(serde_json::Map::new()))
        .as_object_mut()
        .ok_or(ConfigureConfigPatchError::SkillsNotObject)?;

    let builtin = skills
        .entry("builtin".to_string())
        .or_insert_with(|| Value::Object(serde_json::Map::new()))
        .as_object_mut()
        .ok_or(ConfigureConfigPatchError::SkillsBuiltinNotObject)?;
    let builtin_unchanged = builtin.get("tools") == Some(&new_tools);
    if !builtin_unchanged {
        builtin.insert("tools".to_string(), new_tools);
    }

    let allowed: std::collections::HashSet<&str> = tools.iter().map(String::as_str).collect();
    let prev = skills.remove("subagents");
    let subagents_unchanged = match prev {
        Some(Value::Array(arr)) => {
            let kept: Vec<Value> = arr
                .iter()
                .filter(|entry| {
                    entry
                        .as_object()
                        .and_then(|o| o.get("name"))
                        .and_then(Value::as_str)
                        .map(|n| allowed.contains(n))
                        .unwrap_or(false)
                })
                .cloned()
                .collect();
            let unchanged = kept.len() == arr.len() && kept == arr;
            if !kept.is_empty() {
                skills.insert("subagents".to_string(), Value::Array(kept));
            }
            unchanged
        }
        Some(other) => {
            skills.insert("subagents".to_string(), other);
            true
        }
        None => true,
    };

    Ok(!(builtin_unchanged && subagents_unchanged))
}

fn patch_mcp_servers_doc(
    doc: &mut Value,
    servers: &serde_json::Map<String, Value>,
) -> std::result::Result<bool, ConfigureConfigPatchError> {
    let root = doc
        .as_object_mut()
        .ok_or(ConfigureConfigPatchError::RootNotObject)?;
    let new_block = Value::Object(servers.clone());
    if root.get("mcp_servers") == Some(&new_block) {
        return Ok(false);
    }
    if servers.is_empty() {
        root.remove("mcp_servers");
    } else {
        root.insert("mcp_servers".to_string(), new_block);
    }
    Ok(true)
}

fn patch_telegram_controller_doc(
    doc: &mut Value,
    proxy: &TelegramProxyConfigure,
) -> std::result::Result<bool, ConfigureConfigPatchError> {
    let root = doc
        .as_object_mut()
        .ok_or(ConfigureConfigPatchError::RootNotObject)?;
    let controllers = root
        .entry("controllers".to_string())
        .or_insert_with(|| Value::Array(Vec::new()))
        .as_array_mut()
        .ok_or(ConfigureConfigPatchError::RootNotObject)?;

    let desired = serde_json::json!({
        "type": "telegram",
        "mode": "webhook",
        "allow_all_chats": true,
        "enabled": proxy.enabled,
        "proxy": {
            "base_url": proxy.base_url.clone(),
            "file_base_url": proxy.file_base_url.clone(),
            "bearer": proxy.bearer.clone(),
        }
    });

    if let Some(existing) = controllers.iter_mut().find(|entry| {
        entry
            .get("type")
            .and_then(Value::as_str)
            .is_some_and(|kind| kind == "telegram")
    }) {
        if existing == &desired {
            return Ok(false);
        }
        *existing = desired;
        return Ok(true);
    }

    controllers.push(desired);
    Ok(true)
}

async fn write_config_doc(
    path: &std::path::Path,
    doc: &Value,
) -> std::result::Result<(), ConfigureConfigPatchError> {
    let tmp = path.with_extension("json.tmp");
    let pretty = serde_json::to_vec_pretty(doc).map_err(ConfigureConfigPatchError::Serialize)?;
    tokio::fs::write(&tmp, &pretty)
        .await
        .map_err(ConfigureConfigPatchError::WriteTmp)?;
    tokio::fs::rename(&tmp, path)
        .await
        .map_err(ConfigureConfigPatchError::Rename)?;
    Ok(())
}

/// Read dyson.json, patch any of `providers.<agent.provider>.models`,
/// `.api_key`, `.base_url` that the caller supplies, write back
/// atomically.  `None` for a field means "leave alone"; an empty
/// `Some("")` would also be no-op but the caller is expected to filter
/// those out before calling.
///
/// Atomicity matters: `HotReloader` debounces 500ms on mtime so a
/// half-written file isn't a real risk, but rename gives us the
/// belt-and-braces guarantee that a crash mid-write leaves the
/// previous version in place.
#[cfg(test)]
fn patch_provider_in_config(
    path: &std::path::Path,
    models: Option<&[String]>,
    api_key: Option<&str>,
    base_url: Option<&str>,
) -> Result<(), String> {
    let raw = std::fs::read_to_string(path).map_err(|e| format!("read {}: {e}", path.display()))?;
    let mut doc: Value =
        serde_json::from_str(&raw).map_err(|e| format!("parse {}: {e}", path.display()))?;

    let provider_name = doc
        .get("agent")
        .and_then(|a| a.get("provider"))
        .and_then(|p| p.as_str())
        .ok_or_else(|| {
            "config has no agent.provider — can't tell which provider's config to patch".to_string()
        })?
        .to_owned();
    let primary_model = models.and_then(|ms| ms.first().filter(|m| !m.trim().is_empty()).cloned());
    if let Some(primary) = primary_model.as_ref() {
        let agent = doc
            .as_object_mut()
            .ok_or_else(|| "config root is not an object".to_string())?
            .entry("agent".to_string())
            .or_insert_with(|| Value::Object(serde_json::Map::new()))
            .as_object_mut()
            .ok_or_else(|| "config agent is not an object".to_string())?;
        agent.insert("model".into(), Value::String(primary.clone()));
    }

    let providers = doc
        .get_mut("providers")
        .and_then(|p| p.as_object_mut())
        .ok_or_else(|| "config has no providers object".to_string())?;
    let prov_entry = providers
        .get_mut(&provider_name)
        .and_then(|p| p.as_object_mut())
        .ok_or_else(|| format!("config has no providers.{provider_name}"))?;
    if let Some(ms) = models {
        prov_entry.insert(
            "models".into(),
            Value::Array(ms.iter().map(|m| Value::String(m.clone())).collect()),
        );
    }
    if let Some(k) = api_key {
        prov_entry.insert("api_key".into(), Value::String(k.to_owned()));
    }
    if let Some(u) = base_url {
        prov_entry.insert("base_url".into(), Value::String(u.to_owned()));
    }

    // Atomic write: tmp file in same dir + rename.
    let tmp = path.with_extension("json.tmp");
    let pretty = serde_json::to_vec_pretty(&doc).map_err(|e| format!("serialise: {e}"))?;
    std::fs::write(&tmp, &pretty).map_err(|e| format!("write tmp: {e}"))?;
    std::fs::rename(&tmp, path).map_err(|e| format!("rename: {e}"))?;
    Ok(())
}

/// Read dyson.json, register/replace the image-generation provider
/// entry and/or update `agent.image_generation_provider` /
/// `agent.image_generation_model`, write back atomically.  Each input
/// is independent — a `None` means "leave alone" — so a swarm-side
/// rewire can carry only the model change without re-uploading the
/// full provider block, and vice versa.
///
/// Atomicity matters for the same reason as `patch_provider_in_config`:
/// a half-written dyson.json is a chat-killer if the HotReloader picks
/// it up before the second write lands.
#[cfg(test)]
fn patch_image_generation_in_config(
    path: &std::path::Path,
    provider_block: Option<(&str, &Value)>,
    image_provider: Option<&str>,
    image_model: Option<&str>,
) -> Result<(), String> {
    let raw = std::fs::read_to_string(path).map_err(|e| format!("read {}: {e}", path.display()))?;
    let mut doc: Value =
        serde_json::from_str(&raw).map_err(|e| format!("parse {}: {e}", path.display()))?;

    if let Some((name, block)) = provider_block {
        let providers = doc
            .as_object_mut()
            .ok_or_else(|| "config root is not an object".to_string())?
            .entry("providers".to_string())
            .or_insert_with(|| Value::Object(serde_json::Map::new()))
            .as_object_mut()
            .ok_or_else(|| "config providers is not an object".to_string())?;
        providers.insert(name.to_owned(), block.clone());
    }

    if image_provider.is_some() || image_model.is_some() {
        let agent = doc
            .as_object_mut()
            .ok_or_else(|| "config root is not an object".to_string())?
            .entry("agent".to_string())
            .or_insert_with(|| Value::Object(serde_json::Map::new()))
            .as_object_mut()
            .ok_or_else(|| "config agent is not an object".to_string())?;
        if let Some(p) = image_provider {
            agent.insert(
                "image_generation_provider".into(),
                Value::String(p.to_owned()),
            );
        }
        if let Some(m) = image_model {
            agent.insert("image_generation_model".into(), Value::String(m.to_owned()));
        }
    }

    let tmp = path.with_extension("json.tmp");
    let pretty = serde_json::to_vec_pretty(&doc).map_err(|e| format!("serialise: {e}"))?;
    std::fs::write(&tmp, &pretty).map_err(|e| format!("write tmp: {e}"))?;
    std::fs::rename(&tmp, path).map_err(|e| format!("rename: {e}"))?;
    Ok(())
}

/// Drop the `skills` key from dyson.json so the loader's defaults
/// branch registers every builtin tool.  Returns `Ok(true)` when the
/// key was present and removed, `Ok(false)` when it was already
/// absent (no write fired).
///
/// Atomic write via tmp + rename for the same reason as the sibling
/// patch helpers — the HotReloader debounces 500ms on mtime so a
/// half-written file is unlikely, but rename gives us the
/// belt-and-braces guarantee that a crash mid-write leaves the
/// previous version in place.
#[cfg(test)]
fn clear_skills_in_config(path: &std::path::Path) -> Result<bool, String> {
    let raw = std::fs::read_to_string(path).map_err(|e| format!("read {}: {e}", path.display()))?;
    let mut doc: Value =
        serde_json::from_str(&raw).map_err(|e| format!("parse {}: {e}", path.display()))?;
    let removed = doc
        .as_object_mut()
        .ok_or_else(|| "config root is not an object".to_string())?
        .remove("skills")
        .is_some();
    if !removed {
        return Ok(false);
    }
    let tmp = path.with_extension("json.tmp");
    let pretty = serde_json::to_vec_pretty(&doc).map_err(|e| format!("serialise: {e}"))?;
    std::fs::write(&tmp, &pretty).map_err(|e| format!("write tmp: {e}"))?;
    std::fs::rename(&tmp, path).map_err(|e| format!("rename: {e}"))?;
    Ok(true)
}

/// Apply an explicit allowlist to BOTH `skills.builtin.tools` and
/// `skills.subagents`.  The orchestrator's tool-picker UI flattens
/// builtins and subagents into a single checklist, so the two have
/// to share one allowlist — otherwise unchecking a subagent in the
/// SPA leaves it loaded at runtime, and the agent introspects it as
/// available even though the operator disabled it.
///
/// Behaviour:
/// - `skills.builtin.tools` becomes the exact list passed in.  Empty
///   vec lands as `tools: []` so the loader registers zero builtins.
/// - `skills.subagents` is filtered by name: only entries whose
///   `name` appears in the allowlist survive.  An empty allowlist
///   drops the whole `subagents` key (consistent with "register zero
///   subagents", same shape parse_skills uses for an empty agent
///   list — no `Subagent` skill config gets pushed).
/// - Sibling keys under `skills` (locals, anything else) are
///   preserved verbatim.
///
/// Atomic write via tmp + rename, same posture as the sibling
/// helpers.  Returns `Ok(true)` when the file was rewritten,
/// `Ok(false)` when both blocks already matched and no write was
/// needed.
#[cfg(test)]
fn set_skills_tools_in_config(path: &std::path::Path, tools: &[String]) -> Result<bool, String> {
    let raw = std::fs::read_to_string(path).map_err(|e| format!("read {}: {e}", path.display()))?;
    let mut doc: Value =
        serde_json::from_str(&raw).map_err(|e| format!("parse {}: {e}", path.display()))?;
    let root = doc
        .as_object_mut()
        .ok_or_else(|| "config root is not an object".to_string())?;
    let new_tools = Value::Array(tools.iter().map(|t| Value::String(t.clone())).collect());
    let skills = root
        .entry("skills".to_string())
        .or_insert_with(|| Value::Object(serde_json::Map::new()))
        .as_object_mut()
        .ok_or_else(|| "skills is not an object".to_string())?;

    // 1. builtin.tools: rewrite to the exact list.
    let builtin = skills
        .entry("builtin".to_string())
        .or_insert_with(|| Value::Object(serde_json::Map::new()))
        .as_object_mut()
        .ok_or_else(|| "skills.builtin is not an object".to_string())?;
    let builtin_unchanged = builtin.get("tools") == Some(&new_tools);
    if !builtin_unchanged {
        builtin.insert("tools".to_string(), new_tools);
    }

    // 2. subagents: filter by name.  Operate via take/replace so the
    //    skills map can be mutated independently of the read borrow.
    let allowed: std::collections::HashSet<&str> = tools.iter().map(String::as_str).collect();
    let prev = skills.remove("subagents");
    let subagents_unchanged = match prev {
        Some(Value::Array(arr)) => {
            let kept: Vec<Value> = arr
                .iter()
                .filter(|entry| {
                    entry
                        .as_object()
                        .and_then(|o| o.get("name"))
                        .and_then(Value::as_str)
                        .map(|n| allowed.contains(n))
                        .unwrap_or(false)
                })
                .cloned()
                .collect();
            let unchanged = kept.len() == arr.len() && kept == arr;
            if !kept.is_empty() {
                // Re-insert the filtered array — preserves entry
                // ordering and any non-`name` fields per agent.
                skills.insert("subagents".to_string(), Value::Array(kept));
            }
            // kept.is_empty() means the allowlist excludes every
            // subagent — leave the key absent so the loader doesn't
            // push an empty Subagent skill (parse_skills only emits
            // one when the array is non-empty; matching that
            // contract keeps round-trips clean).
            unchanged
        }
        Some(other) => {
            // Malformed pre-existing value (not an array).  Restore
            // it so we don't silently destroy operator state, and
            // treat the call as a no-op for the subagents half.
            skills.insert("subagents".to_string(), other);
            true
        }
        None => {
            // No subagents key — nothing to filter, nothing to write.
            true
        }
    };

    if builtin_unchanged && subagents_unchanged {
        return Ok(false);
    }
    let tmp = path.with_extension("json.tmp");
    let pretty = serde_json::to_vec_pretty(&doc).map_err(|e| format!("serialise: {e}"))?;
    std::fs::write(&tmp, &pretty).map_err(|e| format!("write tmp: {e}"))?;
    std::fs::rename(&tmp, path).map_err(|e| format!("rename: {e}"))?;
    Ok(true)
}

/// Replace the top-level `mcp_servers` block in dyson.json with the
/// supplied map.  Empty map clears the block (loader treats absent
/// and empty identically — no MCP skills register).  Returns
/// `Ok(true)` when the file was rewritten, `Ok(false)` when the
/// existing block already matched and no write was needed.
///
/// Atomic write via tmp + rename — same posture as the sibling
/// helpers above.  HotReloader picks the rewritten file up on the
/// next mtime tick, and the eager-reload at the end of `post()`
/// closes the window between this write and the next agent build.
#[cfg(test)]
fn patch_mcp_servers_in_config(
    path: &std::path::Path,
    servers: &serde_json::Map<String, Value>,
) -> Result<bool, String> {
    let raw = std::fs::read_to_string(path).map_err(|e| format!("read {}: {e}", path.display()))?;
    let mut doc: Value =
        serde_json::from_str(&raw).map_err(|e| format!("parse {}: {e}", path.display()))?;
    let root = doc
        .as_object_mut()
        .ok_or_else(|| "config root is not an object".to_string())?;
    let new_block = Value::Object(servers.clone());
    if root.get("mcp_servers") == Some(&new_block) {
        return Ok(false);
    }
    if servers.is_empty() {
        root.remove("mcp_servers");
    } else {
        root.insert("mcp_servers".to_string(), new_block);
    }
    let tmp = path.with_extension("json.tmp");
    let pretty = serde_json::to_vec_pretty(&doc).map_err(|e| format!("serialise: {e}"))?;
    std::fs::write(&tmp, &pretty).map_err(|e| format!("write tmp: {e}"))?;
    std::fs::rename(&tmp, path).map_err(|e| format!("rename: {e}"))?;
    Ok(true)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn configure_body_accepts_full_swarm_wire_contract() {
        let body: ConfigureBody = serde_json::from_value(serde_json::json!({
            "name": "axelrod",
            "task": "research",
            "models": ["deepseek/deepseek-v4-pro"],
            "instance_id": "i-1",
            "proxy_token": "pt_test",
            "proxy_base": "https://swarm.test/llm/openrouter",
            "image_provider_name": "image",
            "image_provider_block": {
                "type": "openrouter",
                "api_key": "pt_test",
                "models": ["google/gemini-image"]
            },
            "image_generation_provider": "image",
            "image_generation_model": "google/gemini-image",
            "reset_skills": true,
            "tools": ["read_file"],
            "mcp_servers": {
                "massive": { "url": "https://swarm.test/mcp/i-1/massive" }
            },
            "ingest_url": "https://swarm.test/v1/internal/ingest",
            "ingest_token": "it_123",
            "state_sync_url": "https://swarm.test/v1/internal/state/file",
            "state_sync_token": "st_123"
        }))
        .unwrap();

        assert_eq!(body.name.as_deref(), Some("axelrod"));
        assert_eq!(body.models, vec!["deepseek/deepseek-v4-pro"]);
        assert_eq!(body.tools.as_deref(), Some(&["read_file".to_string()][..]));
        assert!(body.reset_skills);
        assert!(body.mcp_servers.as_ref().unwrap().contains_key("massive"));
        assert_eq!(body.state_sync_token.as_deref(), Some("st_123"));
    }

    #[test]
    fn runtime_patch_requires_complete_pairs_and_supports_clear() {
        assert_eq!(
            runtime_patch(
                &Some("https://swarm.test/ingest".into()),
                &Some("it_123".into())
            ),
            Some(RuntimePatch::Set {
                url: "https://swarm.test/ingest",
                token: "it_123"
            })
        );
        assert_eq!(
            runtime_patch(&Some(String::new()), &Some(String::new())),
            Some(RuntimePatch::Clear)
        );
        assert_eq!(
            runtime_patch(&Some("https://swarm.test/ingest".into()), &None),
            None
        );
        assert_eq!(runtime_patch(&None, &Some("it_123".into())), None);
    }

    #[test]
    fn eager_config_reload_preserves_cli_only_sandbox_flag() {
        let snapshot = Settings {
            dangerous_no_sandbox: true,
            ..Default::default()
        };
        let mut reloaded = Settings::default();
        assert!(!reloaded.dangerous_no_sandbox);

        preserve_runtime_only_settings(&mut reloaded, &snapshot);

        assert!(reloaded.dangerous_no_sandbox);
    }

    #[test]
    fn build_identity_md_skips_empty_sections() {
        let s = build_identity_md(Some("Bob"), Some("u1"), None);
        assert!(s.contains("Name: Bob"));
        assert!(s.contains("Swarm instance id: u1"));
        assert!(!s.contains("## Mission"));
    }

    #[test]
    fn build_identity_md_full() {
        let s = build_identity_md(Some("Bob"), Some("u1"), Some("Watch PRs."));
        assert!(s.contains("## Mission\n\nWatch PRs."));
    }

    #[test]
    fn build_identity_md_keeps_full_identity_doc_exact() {
        let full = "# IDENTITY.md — Who Am I?\n\n- **Name:** axelrod";
        let s = build_identity_md(Some("Bob"), Some("u1"), Some(full));
        assert_eq!(s, full);
        assert!(!s.contains("Swarm instance id:"));
        assert!(!s.contains("## Mission"));
    }

    #[test]
    fn existing_full_identity_doc_is_preserved_as_prior_mission() {
        let existing = "# IDENTITY.md — Who Am I?\n\n- **Name:** axelrod";
        let prior = extract_section(existing, "Mission")
            .or_else(|| looks_like_full_identity_doc(existing).then(|| existing.to_owned()));
        assert_eq!(prior.as_deref(), Some(existing));
    }

    #[test]
    fn extract_field_picks_first_match() {
        let b = "Name: Alice\nSwarm instance id: u9\n";
        assert_eq!(extract_field(b, "Name"), Some("Alice".into()));
        assert_eq!(extract_field(b, "Swarm instance id"), Some("u9".into()));
        assert_eq!(extract_field(b, "Missing"), None);
    }

    #[test]
    fn extract_section_keeps_only_named_block() {
        let b = "# Identity\n\nName: A\n\n## Mission\n\nDo the thing.\n\n## Other\n\nelse";
        assert_eq!(extract_section(b, "Mission"), Some("Do the thing.".into()));
        assert_eq!(extract_section(b, "Other"), Some("else".into()));
        assert_eq!(extract_section(b, "Nope"), None);
    }

    #[test]
    fn patch_models_round_trip() {
        use std::io::Write;
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("dyson.json");
        let initial = serde_json::json!({
            "agent": {
                "provider": "openrouter",
                "model": "warmup-placeholder"
            },
            "providers": {
                "openrouter": {
                    "type": "openai",
                    "api_key": "warmup-placeholder",
                    "models": ["warmup-placeholder"]
                }
            }
        });
        let mut f = std::fs::File::create(&path).unwrap();
        f.write_all(serde_json::to_vec_pretty(&initial).unwrap().as_slice())
            .unwrap();
        drop(f);

        // `base_url` must NOT carry `/v1` — `OpenAiCompatClient` appends
        // `/v1/chat/completions` itself when building the request URL.  A
        // base ending in `/v1` doubles up to `/openrouter/v1/v1/...`,
        // which routes to OR's marketing site and surfaces as a generic
        // "upstream HTTP error".
        patch_provider_in_config(
            &path,
            Some(&["anthropic/claude-sonnet-4-5".into(), "openai/gpt-5".into()]),
            Some("dy-real-token"),
            Some("https://dyson.example/llm/openrouter"),
        )
        .unwrap();
        let after: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();
        assert_eq!(
            after["agent"]["model"], "anthropic/claude-sonnet-4-5",
            "reconfigure must clear the boot-time agent.model override"
        );
        let prov = &after["providers"]["openrouter"];
        assert_eq!(prov["api_key"], "dy-real-token");
        assert_eq!(prov["base_url"], "https://dyson.example/llm/openrouter");
        let models = prov["models"].as_array().unwrap();
        assert_eq!(models[0], "anthropic/claude-sonnet-4-5");
        assert_eq!(models[1], "openai/gpt-5");
    }

    #[test]
    fn patch_image_generation_inserts_provider_and_agent_fields() {
        // Existing config has only the chat provider — the swarm-side
        // rewire sweep arrives with a brand-new image provider block
        // and the agent fields pointing at it.  Both must land in one
        // atomic write so the HotReloader doesn't see a half-state.
        use std::io::Write;
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("dyson.json");
        let initial = serde_json::json!({
            "agent": { "provider": "openrouter" },
            "providers": {
                "openrouter": { "type": "openai", "api_key": "x", "models": ["m"] }
            }
        });
        let mut f = std::fs::File::create(&path).unwrap();
        f.write_all(serde_json::to_vec_pretty(&initial).unwrap().as_slice())
            .unwrap();
        drop(f);

        let block = serde_json::json!({
            "type": "openrouter",
            "base_url": "https://swarm/llm/openrouter",
            "api_key": "tok",
            "models": ["google/gemini-3-pro-image-preview"]
        });
        patch_image_generation_in_config(
            &path,
            Some(("openrouter-image", &block)),
            Some("openrouter-image"),
            Some("google/gemini-3-pro-image-preview"),
        )
        .unwrap();

        let after: Value = serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();
        let img = &after["providers"]["openrouter-image"];
        assert_eq!(img["type"], "openrouter");
        assert_eq!(img["base_url"], "https://swarm/llm/openrouter");
        assert_eq!(img["models"][0], "google/gemini-3-pro-image-preview");
        assert_eq!(
            after["agent"]["image_generation_provider"],
            "openrouter-image"
        );
        assert_eq!(
            after["agent"]["image_generation_model"],
            "google/gemini-3-pro-image-preview"
        );
        // Chat side is untouched — a regression here would silently
        // break the chat path on every running instance the sweep
        // visits.
        assert_eq!(after["agent"]["provider"], "openrouter");
        assert_eq!(after["providers"]["openrouter"]["api_key"], "x");
    }

    #[test]
    fn patch_image_generation_partial_update_only_touches_provided_fields() {
        // Operator-side: somebody bumps the image model id (e.g. a
        // newer preview) without changing the provider entry.  Only
        // `agent.image_generation_model` should change; the provider
        // block and provider-name field stay as they were.
        use std::io::Write;
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("dyson.json");
        let initial = serde_json::json!({
            "agent": {
                "provider": "openrouter",
                "image_generation_provider": "openrouter-image",
                "image_generation_model": "google/old-model"
            },
            "providers": {
                "openrouter": { "type": "openai", "api_key": "x", "models": ["m"] },
                "openrouter-image": { "type": "openrouter", "models": ["google/old-model"] }
            }
        });
        let mut f = std::fs::File::create(&path).unwrap();
        f.write_all(serde_json::to_vec_pretty(&initial).unwrap().as_slice())
            .unwrap();
        drop(f);

        patch_image_generation_in_config(&path, None, None, Some("google/new-model")).unwrap();
        let after: Value = serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();
        assert_eq!(after["agent"]["image_generation_model"], "google/new-model");
        assert_eq!(
            after["agent"]["image_generation_provider"],
            "openrouter-image"
        );
        // Provider block models[] left alone — the model id only flows
        // through the agent.image_generation_model override.
        assert_eq!(
            after["providers"]["openrouter-image"]["models"][0],
            "google/old-model"
        );
    }

    #[test]
    fn clear_skills_drops_the_block_so_loader_registers_all_builtins() {
        // Regression for "the agent has no tools".  Older `dyson swarm`
        // boots wrote `skills.builtin.tools = []`, which the loader
        // parses as "register zero builtin tools".  The configure-time
        // skills reset must remove the key entirely so the loader's
        // no-skills-block branch fires on next reload.
        use std::io::Write;
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("dyson.json");
        let initial = serde_json::json!({
            "agent": { "provider": "openrouter" },
            "providers": { "openrouter": { "type": "openai", "api_key": "x", "models": ["m"] } },
            "skills": { "builtin": { "tools": [] } }
        });
        let mut f = std::fs::File::create(&path).unwrap();
        f.write_all(serde_json::to_vec_pretty(&initial).unwrap().as_slice())
            .unwrap();
        drop(f);

        assert!(
            clear_skills_in_config(&path).unwrap(),
            "first call must report a change"
        );
        let after: Value = serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();
        assert!(after.get("skills").is_none(), "skills key must be removed");
        // Other top-level keys unchanged — clearing skills must not
        // perturb providers / agent.
        assert_eq!(after["agent"]["provider"], "openrouter");
        assert_eq!(after["providers"]["openrouter"]["api_key"], "x");

        // Idempotent second call: no skills key means nothing to remove.
        assert!(
            !clear_skills_in_config(&path).unwrap(),
            "second call must report no-op when skills already absent"
        );
    }

    #[test]
    fn set_skills_tools_writes_explicit_allowlist_and_is_idempotent() {
        // Editing an instance's tool selection in the orchestrator UI
        // must rewrite `skills.builtin.tools` to the chosen subset on
        // the running dyson; otherwise the live agent keeps registering
        // the boot-time set.
        use std::io::Write;
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("dyson.json");
        let initial = serde_json::json!({
            "agent": { "provider": "openrouter" },
            "providers": { "openrouter": { "type": "openai", "api_key": "x", "models": ["m"] } }
        });
        let mut f = std::fs::File::create(&path).unwrap();
        f.write_all(serde_json::to_vec_pretty(&initial).unwrap().as_slice())
            .unwrap();
        drop(f);

        let tools = vec!["bash".to_string(), "read_file".to_string()];
        assert!(
            set_skills_tools_in_config(&path, &tools).unwrap(),
            "first write must report a change"
        );
        let after: Value = serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();
        assert_eq!(
            after["skills"]["builtin"]["tools"],
            serde_json::json!(["bash", "read_file"])
        );
        // Sibling keys preserved.
        assert_eq!(after["agent"]["provider"], "openrouter");
        assert_eq!(after["providers"]["openrouter"]["api_key"], "x");

        // Same allowlist a second time is a no-op.
        assert!(
            !set_skills_tools_in_config(&path, &tools).unwrap(),
            "no-change call must report no-op"
        );

        // Empty list lands as `tools: []` so the loader registers zero builtins.
        assert!(
            set_skills_tools_in_config(&path, &[]).unwrap(),
            "shrink to empty must report a change"
        );
        let after: Value = serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();
        assert_eq!(after["skills"]["builtin"]["tools"], serde_json::json!([]));
    }

    #[test]
    fn set_skills_tools_filters_subagents_by_same_allowlist() {
        // The orchestrator's tool-picker collapses builtins and
        // subagents into one checklist; unchecking a subagent in the
        // SPA must drop it from the running dyson too.  Otherwise the
        // agent introspects its loaded subagents and reports them as
        // available even though the operator disabled them — which is
        // the bug this rule fixes.
        use std::io::Write;
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("dyson.json");
        let initial = serde_json::json!({
            "agent": { "provider": "openrouter" },
            "providers": { "openrouter": { "type": "openai", "api_key": "x", "models": ["m"] } },
            "skills": {
                "builtin": { "tools": ["read_file", "write_file"] },
                "subagents": [
                    { "name": "planner",     "description": "p", "system_prompt": "sp" },
                    { "name": "researcher",  "description": "r", "system_prompt": "sr" },
                    { "name": "coder",       "description": "c", "system_prompt": "sc" }
                ]
            }
        });
        let mut f = std::fs::File::create(&path).unwrap();
        f.write_all(serde_json::to_vec_pretty(&initial).unwrap().as_slice())
            .unwrap();
        drop(f);

        // Allowlist keeps two builtins + one of the three subagents.
        let allow = vec![
            "read_file".to_string(),
            "write_file".to_string(),
            "planner".to_string(),
        ];
        assert!(
            set_skills_tools_in_config(&path, &allow).unwrap(),
            "filtering must report a change"
        );
        let after: Value = serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();

        // Builtin allowlist round-trips verbatim — including the two
        // subagent-shaped names.  parse_skills' loader-side filter
        // ignores names that don't match a real builtin, so the only
        // tools that actually register are the genuine builtins.
        assert_eq!(
            after["skills"]["builtin"]["tools"],
            serde_json::json!(["read_file", "write_file", "planner"])
        );

        // Subagents: only "planner" survives; "researcher" and "coder"
        // are gone because they weren't in the allowlist.  The other
        // fields on the kept entry round-trip verbatim.
        let subagents = after["skills"]["subagents"].as_array().unwrap();
        assert_eq!(subagents.len(), 1, "only planner should survive");
        assert_eq!(subagents[0]["name"], "planner");
        assert_eq!(subagents[0]["description"], "p");
        assert_eq!(subagents[0]["system_prompt"], "sp");

        // Same call a second time is a no-op (idempotent).
        assert!(
            !set_skills_tools_in_config(&path, &allow).unwrap(),
            "no-change call must report no-op"
        );

        // Allowlist that excludes every subagent drops the subagents
        // key entirely — keeps the loader's contract that an empty
        // array doesn't get a Subagent skill config pushed.
        let no_subagents = vec!["read_file".to_string()];
        assert!(
            set_skills_tools_in_config(&path, &no_subagents).unwrap(),
            "narrowing the allowlist must report a change"
        );
        let after: Value = serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();
        assert!(
            after["skills"].get("subagents").is_none(),
            "subagents key must be absent when the allowlist excludes every entry, got {:?}",
            after["skills"].get("subagents")
        );
        assert_eq!(
            after["skills"]["builtin"]["tools"],
            serde_json::json!(["read_file"])
        );
    }

    #[test]
    fn patch_mcp_servers_replaces_block_and_is_idempotent() {
        use std::io::Write;
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("dyson.json");
        let initial = serde_json::json!({
            "agent": { "provider": "openrouter" },
            "providers": { "openrouter": { "type": "openai", "api_key": "x", "models": ["m"] } }
        });
        let mut f = std::fs::File::create(&path).unwrap();
        f.write_all(serde_json::to_vec_pretty(&initial).unwrap().as_slice())
            .unwrap();
        drop(f);

        // Insert a server.
        let mut servers = serde_json::Map::new();
        servers.insert(
            "linear".into(),
            serde_json::json!({
                "url": "https://swarm.example/mcp/i-1/linear",
                "headers": { "Authorization": "Bearer tok" }
            }),
        );
        assert!(patch_mcp_servers_in_config(&path, &servers).unwrap());
        let after: Value = serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();
        assert_eq!(
            after["mcp_servers"]["linear"]["url"],
            "https://swarm.example/mcp/i-1/linear"
        );
        // Sibling keys untouched.
        assert_eq!(after["agent"]["provider"], "openrouter");

        // Idempotent: the same map yields no rewrite.
        assert!(!patch_mcp_servers_in_config(&path, &servers).unwrap());

        // Empty map clears the block.
        let empty = serde_json::Map::new();
        assert!(patch_mcp_servers_in_config(&path, &empty).unwrap());
        let after2: Value = serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap();
        assert!(after2.get("mcp_servers").is_none());
    }

    #[test]
    fn clean_relative_path_rejects_escape_paths() {
        assert_eq!(
            clean_relative_path("c-1/transcript.json").unwrap(),
            PathBuf::from("c-1").join("transcript.json")
        );
        assert!(clean_relative_path("../secret").is_err());
        assert!(clean_relative_path("/etc/passwd").is_err());
        assert!(clean_relative_path("c-1/../../secret").is_err());
        assert!(clean_relative_path("c-1\\transcript.json").is_err());
        assert!(clean_relative_path("").is_err());
    }
}
